// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="test,hls_ip_2019_2_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=1,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xczu3eg-sbva484-1-i,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=dataflow,HLS_SYN_CLOCK=8.750000,HLS_SYN_LAT=2447789,HLS_SYN_TPT=1946030,HLS_SYN_MEM=145,HLS_SYN_DSP=257,HLS_SYN_FF=33791,HLS_SYN_LUT=64030,HLS_VERSION=2019_2_1}" *)

module test (
        s_axi_control_AWVALID,
        s_axi_control_AWREADY,
        s_axi_control_AWADDR,
        s_axi_control_WVALID,
        s_axi_control_WREADY,
        s_axi_control_WDATA,
        s_axi_control_WSTRB,
        s_axi_control_ARVALID,
        s_axi_control_ARREADY,
        s_axi_control_ARADDR,
        s_axi_control_RVALID,
        s_axi_control_RREADY,
        s_axi_control_RDATA,
        s_axi_control_RRESP,
        s_axi_control_BVALID,
        s_axi_control_BREADY,
        s_axi_control_BRESP,
        ap_clk,
        ap_rst_n,
        interrupt,
        m_axi_gmem_AWVALID,
        m_axi_gmem_AWREADY,
        m_axi_gmem_AWADDR,
        m_axi_gmem_AWID,
        m_axi_gmem_AWLEN,
        m_axi_gmem_AWSIZE,
        m_axi_gmem_AWBURST,
        m_axi_gmem_AWLOCK,
        m_axi_gmem_AWCACHE,
        m_axi_gmem_AWPROT,
        m_axi_gmem_AWQOS,
        m_axi_gmem_AWREGION,
        m_axi_gmem_AWUSER,
        m_axi_gmem_WVALID,
        m_axi_gmem_WREADY,
        m_axi_gmem_WDATA,
        m_axi_gmem_WSTRB,
        m_axi_gmem_WLAST,
        m_axi_gmem_WID,
        m_axi_gmem_WUSER,
        m_axi_gmem_ARVALID,
        m_axi_gmem_ARREADY,
        m_axi_gmem_ARADDR,
        m_axi_gmem_ARID,
        m_axi_gmem_ARLEN,
        m_axi_gmem_ARSIZE,
        m_axi_gmem_ARBURST,
        m_axi_gmem_ARLOCK,
        m_axi_gmem_ARCACHE,
        m_axi_gmem_ARPROT,
        m_axi_gmem_ARQOS,
        m_axi_gmem_ARREGION,
        m_axi_gmem_ARUSER,
        m_axi_gmem_RVALID,
        m_axi_gmem_RREADY,
        m_axi_gmem_RDATA,
        m_axi_gmem_RLAST,
        m_axi_gmem_RID,
        m_axi_gmem_RUSER,
        m_axi_gmem_RRESP,
        m_axi_gmem_BVALID,
        m_axi_gmem_BREADY,
        m_axi_gmem_BRESP,
        m_axi_gmem_BID,
        m_axi_gmem_BUSER
);

parameter    C_S_AXI_CONTROL_DATA_WIDTH = 32;
parameter    C_S_AXI_CONTROL_ADDR_WIDTH = 5;
parameter    C_S_AXI_DATA_WIDTH = 32;
parameter    C_S_AXI_ADDR_WIDTH = 32;
parameter    C_M_AXI_GMEM_ID_WIDTH = 1;
parameter    C_M_AXI_GMEM_ADDR_WIDTH = 32;
parameter    C_M_AXI_GMEM_DATA_WIDTH = 32;
parameter    C_M_AXI_GMEM_AWUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_ARUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_WUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_RUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_BUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_USER_VALUE = 0;
parameter    C_M_AXI_GMEM_PROT_VALUE = 0;
parameter    C_M_AXI_GMEM_CACHE_VALUE = 3;
parameter    C_M_AXI_ID_WIDTH = 1;
parameter    C_M_AXI_ADDR_WIDTH = 32;
parameter    C_M_AXI_DATA_WIDTH = 32;
parameter    C_M_AXI_AWUSER_WIDTH = 1;
parameter    C_M_AXI_ARUSER_WIDTH = 1;
parameter    C_M_AXI_WUSER_WIDTH = 1;
parameter    C_M_AXI_RUSER_WIDTH = 1;
parameter    C_M_AXI_BUSER_WIDTH = 1;

parameter C_S_AXI_CONTROL_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_GMEM_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_WSTRB_WIDTH = (32 / 8);

input   s_axi_control_AWVALID;
output   s_axi_control_AWREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_AWADDR;
input   s_axi_control_WVALID;
output   s_axi_control_WREADY;
input  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_WDATA;
input  [C_S_AXI_CONTROL_WSTRB_WIDTH - 1:0] s_axi_control_WSTRB;
input   s_axi_control_ARVALID;
output   s_axi_control_ARREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_ARADDR;
output   s_axi_control_RVALID;
input   s_axi_control_RREADY;
output  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_RDATA;
output  [1:0] s_axi_control_RRESP;
output   s_axi_control_BVALID;
input   s_axi_control_BREADY;
output  [1:0] s_axi_control_BRESP;
input   ap_clk;
input   ap_rst_n;
output   interrupt;
output   m_axi_gmem_AWVALID;
input   m_axi_gmem_AWREADY;
output  [C_M_AXI_GMEM_ADDR_WIDTH - 1:0] m_axi_gmem_AWADDR;
output  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_gmem_AWID;
output  [7:0] m_axi_gmem_AWLEN;
output  [2:0] m_axi_gmem_AWSIZE;
output  [1:0] m_axi_gmem_AWBURST;
output  [1:0] m_axi_gmem_AWLOCK;
output  [3:0] m_axi_gmem_AWCACHE;
output  [2:0] m_axi_gmem_AWPROT;
output  [3:0] m_axi_gmem_AWQOS;
output  [3:0] m_axi_gmem_AWREGION;
output  [C_M_AXI_GMEM_AWUSER_WIDTH - 1:0] m_axi_gmem_AWUSER;
output   m_axi_gmem_WVALID;
input   m_axi_gmem_WREADY;
output  [C_M_AXI_GMEM_DATA_WIDTH - 1:0] m_axi_gmem_WDATA;
output  [C_M_AXI_GMEM_WSTRB_WIDTH - 1:0] m_axi_gmem_WSTRB;
output   m_axi_gmem_WLAST;
output  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_gmem_WID;
output  [C_M_AXI_GMEM_WUSER_WIDTH - 1:0] m_axi_gmem_WUSER;
output   m_axi_gmem_ARVALID;
input   m_axi_gmem_ARREADY;
output  [C_M_AXI_GMEM_ADDR_WIDTH - 1:0] m_axi_gmem_ARADDR;
output  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_gmem_ARID;
output  [7:0] m_axi_gmem_ARLEN;
output  [2:0] m_axi_gmem_ARSIZE;
output  [1:0] m_axi_gmem_ARBURST;
output  [1:0] m_axi_gmem_ARLOCK;
output  [3:0] m_axi_gmem_ARCACHE;
output  [2:0] m_axi_gmem_ARPROT;
output  [3:0] m_axi_gmem_ARQOS;
output  [3:0] m_axi_gmem_ARREGION;
output  [C_M_AXI_GMEM_ARUSER_WIDTH - 1:0] m_axi_gmem_ARUSER;
input   m_axi_gmem_RVALID;
output   m_axi_gmem_RREADY;
input  [C_M_AXI_GMEM_DATA_WIDTH - 1:0] m_axi_gmem_RDATA;
input   m_axi_gmem_RLAST;
input  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_gmem_RID;
input  [C_M_AXI_GMEM_RUSER_WIDTH - 1:0] m_axi_gmem_RUSER;
input  [1:0] m_axi_gmem_RRESP;
input   m_axi_gmem_BVALID;
output   m_axi_gmem_BREADY;
input  [1:0] m_axi_gmem_BRESP;
input  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_gmem_BID;
input  [C_M_AXI_GMEM_BUSER_WIDTH - 1:0] m_axi_gmem_BUSER;

 reg    ap_rst_n_inv;
wire    ap_start;
wire    ap_ready;
wire    ap_done;
wire    ap_idle;
wire   [31:0] input_image;
wire   [31:0] result;
wire    gmem_AWREADY;
wire    gmem_WREADY;
wire    gmem_ARREADY;
wire    gmem_RVALID;
wire   [31:0] gmem_RDATA;
wire    gmem_RLAST;
wire   [0:0] gmem_RID;
wire   [0:0] gmem_RUSER;
wire   [1:0] gmem_RRESP;
wire    gmem_BVALID;
wire   [1:0] gmem_BRESP;
wire   [0:0] gmem_BID;
wire   [0:0] gmem_BUSER;
wire    conv113_U0_ap_start;
wire    conv113_U0_start_full_n;
wire    conv113_U0_ap_done;
wire    conv113_U0_ap_continue;
wire    conv113_U0_ap_idle;
wire    conv113_U0_ap_ready;
wire    conv113_U0_start_out;
wire    conv113_U0_start_write;
wire    conv113_U0_m_axi_input_image_AWVALID;
wire   [31:0] conv113_U0_m_axi_input_image_AWADDR;
wire   [0:0] conv113_U0_m_axi_input_image_AWID;
wire   [31:0] conv113_U0_m_axi_input_image_AWLEN;
wire   [2:0] conv113_U0_m_axi_input_image_AWSIZE;
wire   [1:0] conv113_U0_m_axi_input_image_AWBURST;
wire   [1:0] conv113_U0_m_axi_input_image_AWLOCK;
wire   [3:0] conv113_U0_m_axi_input_image_AWCACHE;
wire   [2:0] conv113_U0_m_axi_input_image_AWPROT;
wire   [3:0] conv113_U0_m_axi_input_image_AWQOS;
wire   [3:0] conv113_U0_m_axi_input_image_AWREGION;
wire   [0:0] conv113_U0_m_axi_input_image_AWUSER;
wire    conv113_U0_m_axi_input_image_WVALID;
wire   [31:0] conv113_U0_m_axi_input_image_WDATA;
wire   [3:0] conv113_U0_m_axi_input_image_WSTRB;
wire    conv113_U0_m_axi_input_image_WLAST;
wire   [0:0] conv113_U0_m_axi_input_image_WID;
wire   [0:0] conv113_U0_m_axi_input_image_WUSER;
wire    conv113_U0_m_axi_input_image_ARVALID;
wire   [31:0] conv113_U0_m_axi_input_image_ARADDR;
wire   [0:0] conv113_U0_m_axi_input_image_ARID;
wire   [31:0] conv113_U0_m_axi_input_image_ARLEN;
wire   [2:0] conv113_U0_m_axi_input_image_ARSIZE;
wire   [1:0] conv113_U0_m_axi_input_image_ARBURST;
wire   [1:0] conv113_U0_m_axi_input_image_ARLOCK;
wire   [3:0] conv113_U0_m_axi_input_image_ARCACHE;
wire   [2:0] conv113_U0_m_axi_input_image_ARPROT;
wire   [3:0] conv113_U0_m_axi_input_image_ARQOS;
wire   [3:0] conv113_U0_m_axi_input_image_ARREGION;
wire   [0:0] conv113_U0_m_axi_input_image_ARUSER;
wire    conv113_U0_m_axi_input_image_RREADY;
wire    conv113_U0_m_axi_input_image_BREADY;
wire   [15:0] conv113_U0_conv1_pipe_1_V_V_din;
wire    conv113_U0_conv1_pipe_1_V_V_write;
wire   [31:0] conv113_U0_result_out_din;
wire    conv113_U0_result_out_write;
wire    relu_bn1_U0_ap_start;
wire    relu_bn1_U0_ap_done;
wire    relu_bn1_U0_ap_continue;
wire    relu_bn1_U0_ap_idle;
wire    relu_bn1_U0_ap_ready;
wire    relu_bn1_U0_start_out;
wire    relu_bn1_U0_start_write;
wire    relu_bn1_U0_conv1_pipe_1_V_V_read;
wire   [4:0] relu_bn1_U0_relu1_pipe_2_V_V_din;
wire    relu_bn1_U0_relu1_pipe_2_V_V_write;
wire    maxpool1_U0_ap_start;
wire    maxpool1_U0_ap_done;
wire    maxpool1_U0_ap_continue;
wire    maxpool1_U0_ap_idle;
wire    maxpool1_U0_ap_ready;
wire    maxpool1_U0_start_out;
wire    maxpool1_U0_start_write;
wire    maxpool1_U0_relu1_pipe_2_V_V_read;
wire   [4:0] maxpool1_U0_pool1_pipe_2_V_V_din;
wire    maxpool1_U0_pool1_pipe_2_V_V_write;
wire    conv2_U0_ap_start;
wire    conv2_U0_ap_done;
wire    conv2_U0_ap_continue;
wire    conv2_U0_ap_idle;
wire    conv2_U0_ap_ready;
wire    conv2_U0_start_out;
wire    conv2_U0_start_write;
wire    conv2_U0_pool1_pipe_2_V_V_read;
wire   [15:0] conv2_U0_conv2_pipe_3_V_V_din;
wire    conv2_U0_conv2_pipe_3_V_V_write;
wire    relu_bn2_U0_ap_start;
wire    relu_bn2_U0_ap_done;
wire    relu_bn2_U0_ap_continue;
wire    relu_bn2_U0_ap_idle;
wire    relu_bn2_U0_ap_ready;
wire    relu_bn2_U0_start_out;
wire    relu_bn2_U0_start_write;
wire    relu_bn2_U0_conv2_pipe_3_V_V_read;
wire   [4:0] relu_bn2_U0_relu2_pipe_4_V_V_din;
wire    relu_bn2_U0_relu2_pipe_4_V_V_write;
wire    maxpool2_U0_ap_start;
wire    maxpool2_U0_ap_done;
wire    maxpool2_U0_ap_continue;
wire    maxpool2_U0_ap_idle;
wire    maxpool2_U0_ap_ready;
wire    maxpool2_U0_start_out;
wire    maxpool2_U0_start_write;
wire    maxpool2_U0_relu2_pipe_4_V_V_read;
wire   [4:0] maxpool2_U0_pool2_pipe_4_V_V_din;
wire    maxpool2_U0_pool2_pipe_4_V_V_write;
wire    conv3_U0_ap_start;
wire    conv3_U0_ap_done;
wire    conv3_U0_ap_continue;
wire    conv3_U0_ap_idle;
wire    conv3_U0_ap_ready;
wire    conv3_U0_start_out;
wire    conv3_U0_start_write;
wire    conv3_U0_pool2_pipe_4_V_V_read;
wire   [15:0] conv3_U0_conv3_pipe_5_V_V_din;
wire    conv3_U0_conv3_pipe_5_V_V_write;
wire    relu_bn3_U0_ap_start;
wire    relu_bn3_U0_ap_done;
wire    relu_bn3_U0_ap_continue;
wire    relu_bn3_U0_ap_idle;
wire    relu_bn3_U0_ap_ready;
wire    relu_bn3_U0_start_out;
wire    relu_bn3_U0_start_write;
wire    relu_bn3_U0_conv3_pipe_5_V_V_read;
wire   [4:0] relu_bn3_U0_relu3_pipe_6_V_V_din;
wire    relu_bn3_U0_relu3_pipe_6_V_V_write;
wire    maxpool3_U0_ap_start;
wire    maxpool3_U0_ap_done;
wire    maxpool3_U0_ap_continue;
wire    maxpool3_U0_ap_idle;
wire    maxpool3_U0_ap_ready;
wire    maxpool3_U0_start_out;
wire    maxpool3_U0_start_write;
wire    maxpool3_U0_relu3_pipe_6_V_V_read;
wire   [4:0] maxpool3_U0_pool3_pipe_6_V_V_din;
wire    maxpool3_U0_pool3_pipe_6_V_V_write;
wire    conv4_U0_ap_start;
wire    conv4_U0_ap_done;
wire    conv4_U0_ap_continue;
wire    conv4_U0_ap_idle;
wire    conv4_U0_ap_ready;
wire    conv4_U0_start_out;
wire    conv4_U0_start_write;
wire    conv4_U0_pool3_pipe_6_V_V_read;
wire   [15:0] conv4_U0_conv4_pipe_7_V_V_din;
wire    conv4_U0_conv4_pipe_7_V_V_write;
wire    relu_bn4_U0_ap_start;
wire    relu_bn4_U0_ap_done;
wire    relu_bn4_U0_ap_continue;
wire    relu_bn4_U0_ap_idle;
wire    relu_bn4_U0_ap_ready;
wire    relu_bn4_U0_start_out;
wire    relu_bn4_U0_start_write;
wire    relu_bn4_U0_conv4_pipe_7_V_V_read;
wire   [4:0] relu_bn4_U0_relu4_pipe_8_V_V_din;
wire    relu_bn4_U0_relu4_pipe_8_V_V_write;
wire    maxpool4_U0_ap_start;
wire    maxpool4_U0_ap_done;
wire    maxpool4_U0_ap_continue;
wire    maxpool4_U0_ap_idle;
wire    maxpool4_U0_ap_ready;
wire    maxpool4_U0_start_out;
wire    maxpool4_U0_start_write;
wire    maxpool4_U0_relu4_pipe_8_V_V_read;
wire   [4:0] maxpool4_U0_pool4_pipe_8_V_V_din;
wire    maxpool4_U0_pool4_pipe_8_V_V_write;
wire    conv5_U0_ap_start;
wire    conv5_U0_ap_done;
wire    conv5_U0_ap_continue;
wire    conv5_U0_ap_idle;
wire    conv5_U0_ap_ready;
wire    conv5_U0_start_out;
wire    conv5_U0_start_write;
wire    conv5_U0_pool4_pipe_8_V_V_read;
wire   [15:0] conv5_U0_conv5_pipe_9_V_V_din;
wire    conv5_U0_conv5_pipe_9_V_V_write;
wire    relu_bn5_U0_ap_start;
wire    relu_bn5_U0_ap_done;
wire    relu_bn5_U0_ap_continue;
wire    relu_bn5_U0_ap_idle;
wire    relu_bn5_U0_ap_ready;
wire    relu_bn5_U0_start_out;
wire    relu_bn5_U0_start_write;
wire    relu_bn5_U0_conv5_pipe_9_V_V_read;
wire   [4:0] relu_bn5_U0_relu5_pipe_10_V_V_din;
wire    relu_bn5_U0_relu5_pipe_10_V_V_write;
wire    conv6_U0_ap_start;
wire    conv6_U0_ap_done;
wire    conv6_U0_ap_continue;
wire    conv6_U0_ap_idle;
wire    conv6_U0_ap_ready;
wire    conv6_U0_start_out;
wire    conv6_U0_start_write;
wire    conv6_U0_relu5_pipe_10_V_V_read;
wire   [15:0] conv6_U0_conv6_pipe_11_V_V_din;
wire    conv6_U0_conv6_pipe_11_V_V_write;
wire    relu_bn6_U0_ap_start;
wire    relu_bn6_U0_ap_done;
wire    relu_bn6_U0_ap_continue;
wire    relu_bn6_U0_ap_idle;
wire    relu_bn6_U0_ap_ready;
wire    relu_bn6_U0_start_out;
wire    relu_bn6_U0_start_write;
wire    relu_bn6_U0_conv6_pipe_11_V_V_read;
wire   [4:0] relu_bn6_U0_relu6_pipe_12_V_V_din;
wire    relu_bn6_U0_relu6_pipe_12_V_V_write;
wire    conv7_U0_ap_start;
wire    conv7_U0_ap_done;
wire    conv7_U0_ap_continue;
wire    conv7_U0_ap_idle;
wire    conv7_U0_ap_ready;
wire    conv7_U0_start_out;
wire    conv7_U0_start_write;
wire    conv7_U0_relu6_pipe_12_V_V_read;
wire   [15:0] conv7_U0_conv7_pipe_13_V_V_din;
wire    conv7_U0_conv7_pipe_13_V_V_write;
wire    relu_bn7_U0_ap_start;
wire    relu_bn7_U0_ap_done;
wire    relu_bn7_U0_ap_continue;
wire    relu_bn7_U0_ap_idle;
wire    relu_bn7_U0_ap_ready;
wire    relu_bn7_U0_start_out;
wire    relu_bn7_U0_start_write;
wire    relu_bn7_U0_conv7_pipe_13_V_V_read;
wire   [4:0] relu_bn7_U0_relu7_pipe_14_V_V_din;
wire    relu_bn7_U0_relu7_pipe_14_V_V_write;
wire    conv8_U0_ap_start;
wire    conv8_U0_ap_done;
wire    conv8_U0_ap_continue;
wire    conv8_U0_ap_idle;
wire    conv8_U0_ap_ready;
wire    conv8_U0_relu7_pipe_14_V_V_read;
wire   [15:0] conv8_U0_conv8_pipe_15_V_V_din;
wire    conv8_U0_conv8_pipe_15_V_V_write;
wire    relu_bn8_U0_ap_start;
wire    relu_bn8_U0_ap_done;
wire    relu_bn8_U0_ap_continue;
wire    relu_bn8_U0_ap_idle;
wire    relu_bn8_U0_ap_ready;
wire    relu_bn8_U0_conv8_pipe_15_V_V_read;
wire    relu_bn8_U0_m_axi_result_AWVALID;
wire   [31:0] relu_bn8_U0_m_axi_result_AWADDR;
wire   [0:0] relu_bn8_U0_m_axi_result_AWID;
wire   [31:0] relu_bn8_U0_m_axi_result_AWLEN;
wire   [2:0] relu_bn8_U0_m_axi_result_AWSIZE;
wire   [1:0] relu_bn8_U0_m_axi_result_AWBURST;
wire   [1:0] relu_bn8_U0_m_axi_result_AWLOCK;
wire   [3:0] relu_bn8_U0_m_axi_result_AWCACHE;
wire   [2:0] relu_bn8_U0_m_axi_result_AWPROT;
wire   [3:0] relu_bn8_U0_m_axi_result_AWQOS;
wire   [3:0] relu_bn8_U0_m_axi_result_AWREGION;
wire   [0:0] relu_bn8_U0_m_axi_result_AWUSER;
wire    relu_bn8_U0_m_axi_result_WVALID;
wire   [31:0] relu_bn8_U0_m_axi_result_WDATA;
wire   [3:0] relu_bn8_U0_m_axi_result_WSTRB;
wire    relu_bn8_U0_m_axi_result_WLAST;
wire   [0:0] relu_bn8_U0_m_axi_result_WID;
wire   [0:0] relu_bn8_U0_m_axi_result_WUSER;
wire    relu_bn8_U0_m_axi_result_ARVALID;
wire   [31:0] relu_bn8_U0_m_axi_result_ARADDR;
wire   [0:0] relu_bn8_U0_m_axi_result_ARID;
wire   [31:0] relu_bn8_U0_m_axi_result_ARLEN;
wire   [2:0] relu_bn8_U0_m_axi_result_ARSIZE;
wire   [1:0] relu_bn8_U0_m_axi_result_ARBURST;
wire   [1:0] relu_bn8_U0_m_axi_result_ARLOCK;
wire   [3:0] relu_bn8_U0_m_axi_result_ARCACHE;
wire   [2:0] relu_bn8_U0_m_axi_result_ARPROT;
wire   [3:0] relu_bn8_U0_m_axi_result_ARQOS;
wire   [3:0] relu_bn8_U0_m_axi_result_ARREGION;
wire   [0:0] relu_bn8_U0_m_axi_result_ARUSER;
wire    relu_bn8_U0_m_axi_result_RREADY;
wire    relu_bn8_U0_m_axi_result_BREADY;
wire    relu_bn8_U0_result_offset_read;
wire    ap_sync_continue;
wire    conv1_pipe_1_V_V_full_n;
wire   [15:0] conv1_pipe_1_V_V_dout;
wire    conv1_pipe_1_V_V_empty_n;
wire    result_c_full_n;
wire   [31:0] result_c_dout;
wire    result_c_empty_n;
wire    relu1_pipe_2_V_V_full_n;
wire   [4:0] relu1_pipe_2_V_V_dout;
wire    relu1_pipe_2_V_V_empty_n;
wire    pool1_pipe_2_V_V_full_n;
wire   [4:0] pool1_pipe_2_V_V_dout;
wire    pool1_pipe_2_V_V_empty_n;
wire    conv2_pipe_3_V_V_full_n;
wire   [15:0] conv2_pipe_3_V_V_dout;
wire    conv2_pipe_3_V_V_empty_n;
wire    relu2_pipe_4_V_V_full_n;
wire   [4:0] relu2_pipe_4_V_V_dout;
wire    relu2_pipe_4_V_V_empty_n;
wire    pool2_pipe_4_V_V_full_n;
wire   [4:0] pool2_pipe_4_V_V_dout;
wire    pool2_pipe_4_V_V_empty_n;
wire    conv3_pipe_5_V_V_full_n;
wire   [15:0] conv3_pipe_5_V_V_dout;
wire    conv3_pipe_5_V_V_empty_n;
wire    relu3_pipe_6_V_V_full_n;
wire   [4:0] relu3_pipe_6_V_V_dout;
wire    relu3_pipe_6_V_V_empty_n;
wire    pool3_pipe_6_V_V_full_n;
wire   [4:0] pool3_pipe_6_V_V_dout;
wire    pool3_pipe_6_V_V_empty_n;
wire    conv4_pipe_7_V_V_full_n;
wire   [15:0] conv4_pipe_7_V_V_dout;
wire    conv4_pipe_7_V_V_empty_n;
wire    relu4_pipe_8_V_V_full_n;
wire   [4:0] relu4_pipe_8_V_V_dout;
wire    relu4_pipe_8_V_V_empty_n;
wire    pool4_pipe_8_V_V_full_n;
wire   [4:0] pool4_pipe_8_V_V_dout;
wire    pool4_pipe_8_V_V_empty_n;
wire    conv5_pipe_9_V_V_full_n;
wire   [15:0] conv5_pipe_9_V_V_dout;
wire    conv5_pipe_9_V_V_empty_n;
wire    relu5_pipe_10_V_V_full_n;
wire   [4:0] relu5_pipe_10_V_V_dout;
wire    relu5_pipe_10_V_V_empty_n;
wire    conv6_pipe_11_V_V_full_n;
wire   [15:0] conv6_pipe_11_V_V_dout;
wire    conv6_pipe_11_V_V_empty_n;
wire    relu6_pipe_12_V_V_full_n;
wire   [4:0] relu6_pipe_12_V_V_dout;
wire    relu6_pipe_12_V_V_empty_n;
wire    conv7_pipe_13_V_V_full_n;
wire   [15:0] conv7_pipe_13_V_V_dout;
wire    conv7_pipe_13_V_V_empty_n;
wire    relu7_pipe_14_V_V_full_n;
wire   [4:0] relu7_pipe_14_V_V_dout;
wire    relu7_pipe_14_V_V_empty_n;
wire    conv8_pipe_15_V_V_full_n;
wire   [15:0] conv8_pipe_15_V_V_dout;
wire    conv8_pipe_15_V_V_empty_n;
wire    ap_sync_done;
wire    ap_sync_ready;
wire   [0:0] start_for_relu_bn1_U0_din;
wire    start_for_relu_bn1_U0_full_n;
wire   [0:0] start_for_relu_bn1_U0_dout;
wire    start_for_relu_bn1_U0_empty_n;
wire   [0:0] start_for_relu_bn8_U0_din;
wire    start_for_relu_bn8_U0_full_n;
wire   [0:0] start_for_relu_bn8_U0_dout;
wire    start_for_relu_bn8_U0_empty_n;
wire   [0:0] start_for_maxpool1_U0_din;
wire    start_for_maxpool1_U0_full_n;
wire   [0:0] start_for_maxpool1_U0_dout;
wire    start_for_maxpool1_U0_empty_n;
wire   [0:0] start_for_conv2_U0_din;
wire    start_for_conv2_U0_full_n;
wire   [0:0] start_for_conv2_U0_dout;
wire    start_for_conv2_U0_empty_n;
wire   [0:0] start_for_relu_bn2_U0_din;
wire    start_for_relu_bn2_U0_full_n;
wire   [0:0] start_for_relu_bn2_U0_dout;
wire    start_for_relu_bn2_U0_empty_n;
wire   [0:0] start_for_maxpool2_U0_din;
wire    start_for_maxpool2_U0_full_n;
wire   [0:0] start_for_maxpool2_U0_dout;
wire    start_for_maxpool2_U0_empty_n;
wire   [0:0] start_for_conv3_U0_din;
wire    start_for_conv3_U0_full_n;
wire   [0:0] start_for_conv3_U0_dout;
wire    start_for_conv3_U0_empty_n;
wire   [0:0] start_for_relu_bn3_U0_din;
wire    start_for_relu_bn3_U0_full_n;
wire   [0:0] start_for_relu_bn3_U0_dout;
wire    start_for_relu_bn3_U0_empty_n;
wire   [0:0] start_for_maxpool3_U0_din;
wire    start_for_maxpool3_U0_full_n;
wire   [0:0] start_for_maxpool3_U0_dout;
wire    start_for_maxpool3_U0_empty_n;
wire   [0:0] start_for_conv4_U0_din;
wire    start_for_conv4_U0_full_n;
wire   [0:0] start_for_conv4_U0_dout;
wire    start_for_conv4_U0_empty_n;
wire   [0:0] start_for_relu_bn4_U0_din;
wire    start_for_relu_bn4_U0_full_n;
wire   [0:0] start_for_relu_bn4_U0_dout;
wire    start_for_relu_bn4_U0_empty_n;
wire   [0:0] start_for_maxpool4_U0_din;
wire    start_for_maxpool4_U0_full_n;
wire   [0:0] start_for_maxpool4_U0_dout;
wire    start_for_maxpool4_U0_empty_n;
wire   [0:0] start_for_conv5_U0_din;
wire    start_for_conv5_U0_full_n;
wire   [0:0] start_for_conv5_U0_dout;
wire    start_for_conv5_U0_empty_n;
wire   [0:0] start_for_relu_bn5_U0_din;
wire    start_for_relu_bn5_U0_full_n;
wire   [0:0] start_for_relu_bn5_U0_dout;
wire    start_for_relu_bn5_U0_empty_n;
wire   [0:0] start_for_conv6_U0_din;
wire    start_for_conv6_U0_full_n;
wire   [0:0] start_for_conv6_U0_dout;
wire    start_for_conv6_U0_empty_n;
wire   [0:0] start_for_relu_bn6_U0_din;
wire    start_for_relu_bn6_U0_full_n;
wire   [0:0] start_for_relu_bn6_U0_dout;
wire    start_for_relu_bn6_U0_empty_n;
wire   [0:0] start_for_conv7_U0_din;
wire    start_for_conv7_U0_full_n;
wire   [0:0] start_for_conv7_U0_dout;
wire    start_for_conv7_U0_empty_n;
wire   [0:0] start_for_relu_bn7_U0_din;
wire    start_for_relu_bn7_U0_full_n;
wire   [0:0] start_for_relu_bn7_U0_dout;
wire    start_for_relu_bn7_U0_empty_n;
wire   [0:0] start_for_conv8_U0_din;
wire    start_for_conv8_U0_full_n;
wire   [0:0] start_for_conv8_U0_dout;
wire    start_for_conv8_U0_empty_n;
wire    conv8_U0_start_full_n;
wire    conv8_U0_start_write;
wire    relu_bn8_U0_start_full_n;
wire    relu_bn8_U0_start_write;

test_control_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CONTROL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CONTROL_DATA_WIDTH ))
test_control_s_axi_U(
    .AWVALID(s_axi_control_AWVALID),
    .AWREADY(s_axi_control_AWREADY),
    .AWADDR(s_axi_control_AWADDR),
    .WVALID(s_axi_control_WVALID),
    .WREADY(s_axi_control_WREADY),
    .WDATA(s_axi_control_WDATA),
    .WSTRB(s_axi_control_WSTRB),
    .ARVALID(s_axi_control_ARVALID),
    .ARREADY(s_axi_control_ARREADY),
    .ARADDR(s_axi_control_ARADDR),
    .RVALID(s_axi_control_RVALID),
    .RREADY(s_axi_control_RREADY),
    .RDATA(s_axi_control_RDATA),
    .RRESP(s_axi_control_RRESP),
    .BVALID(s_axi_control_BVALID),
    .BREADY(s_axi_control_BREADY),
    .BRESP(s_axi_control_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_idle(ap_idle),
    .input_image(input_image),
    .result(result)
);

test_gmem_m_axi #(
    .CONSERVATIVE( 0 ),
    .USER_DW( 32 ),
    .USER_AW( 32 ),
    .USER_MAXREQS( 5 ),
    .NUM_READ_OUTSTANDING( 16 ),
    .NUM_WRITE_OUTSTANDING( 16 ),
    .MAX_READ_BURST_LENGTH( 16 ),
    .MAX_WRITE_BURST_LENGTH( 16 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_GMEM_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_GMEM_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_GMEM_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_GMEM_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_GMEM_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_GMEM_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_GMEM_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_GMEM_BUSER_WIDTH ),
    .C_USER_VALUE( C_M_AXI_GMEM_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_GMEM_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_GMEM_CACHE_VALUE ))
test_gmem_m_axi_U(
    .AWVALID(m_axi_gmem_AWVALID),
    .AWREADY(m_axi_gmem_AWREADY),
    .AWADDR(m_axi_gmem_AWADDR),
    .AWID(m_axi_gmem_AWID),
    .AWLEN(m_axi_gmem_AWLEN),
    .AWSIZE(m_axi_gmem_AWSIZE),
    .AWBURST(m_axi_gmem_AWBURST),
    .AWLOCK(m_axi_gmem_AWLOCK),
    .AWCACHE(m_axi_gmem_AWCACHE),
    .AWPROT(m_axi_gmem_AWPROT),
    .AWQOS(m_axi_gmem_AWQOS),
    .AWREGION(m_axi_gmem_AWREGION),
    .AWUSER(m_axi_gmem_AWUSER),
    .WVALID(m_axi_gmem_WVALID),
    .WREADY(m_axi_gmem_WREADY),
    .WDATA(m_axi_gmem_WDATA),
    .WSTRB(m_axi_gmem_WSTRB),
    .WLAST(m_axi_gmem_WLAST),
    .WID(m_axi_gmem_WID),
    .WUSER(m_axi_gmem_WUSER),
    .ARVALID(m_axi_gmem_ARVALID),
    .ARREADY(m_axi_gmem_ARREADY),
    .ARADDR(m_axi_gmem_ARADDR),
    .ARID(m_axi_gmem_ARID),
    .ARLEN(m_axi_gmem_ARLEN),
    .ARSIZE(m_axi_gmem_ARSIZE),
    .ARBURST(m_axi_gmem_ARBURST),
    .ARLOCK(m_axi_gmem_ARLOCK),
    .ARCACHE(m_axi_gmem_ARCACHE),
    .ARPROT(m_axi_gmem_ARPROT),
    .ARQOS(m_axi_gmem_ARQOS),
    .ARREGION(m_axi_gmem_ARREGION),
    .ARUSER(m_axi_gmem_ARUSER),
    .RVALID(m_axi_gmem_RVALID),
    .RREADY(m_axi_gmem_RREADY),
    .RDATA(m_axi_gmem_RDATA),
    .RLAST(m_axi_gmem_RLAST),
    .RID(m_axi_gmem_RID),
    .RUSER(m_axi_gmem_RUSER),
    .RRESP(m_axi_gmem_RRESP),
    .BVALID(m_axi_gmem_BVALID),
    .BREADY(m_axi_gmem_BREADY),
    .BRESP(m_axi_gmem_BRESP),
    .BID(m_axi_gmem_BID),
    .BUSER(m_axi_gmem_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_ARVALID(conv113_U0_m_axi_input_image_ARVALID),
    .I_ARREADY(gmem_ARREADY),
    .I_ARADDR(conv113_U0_m_axi_input_image_ARADDR),
    .I_ARID(conv113_U0_m_axi_input_image_ARID),
    .I_ARLEN(conv113_U0_m_axi_input_image_ARLEN),
    .I_ARSIZE(conv113_U0_m_axi_input_image_ARSIZE),
    .I_ARLOCK(conv113_U0_m_axi_input_image_ARLOCK),
    .I_ARCACHE(conv113_U0_m_axi_input_image_ARCACHE),
    .I_ARQOS(conv113_U0_m_axi_input_image_ARQOS),
    .I_ARPROT(conv113_U0_m_axi_input_image_ARPROT),
    .I_ARUSER(conv113_U0_m_axi_input_image_ARUSER),
    .I_ARBURST(conv113_U0_m_axi_input_image_ARBURST),
    .I_ARREGION(conv113_U0_m_axi_input_image_ARREGION),
    .I_RVALID(gmem_RVALID),
    .I_RREADY(conv113_U0_m_axi_input_image_RREADY),
    .I_RDATA(gmem_RDATA),
    .I_RID(gmem_RID),
    .I_RUSER(gmem_RUSER),
    .I_RRESP(gmem_RRESP),
    .I_RLAST(gmem_RLAST),
    .I_AWVALID(relu_bn8_U0_m_axi_result_AWVALID),
    .I_AWREADY(gmem_AWREADY),
    .I_AWADDR(relu_bn8_U0_m_axi_result_AWADDR),
    .I_AWID(relu_bn8_U0_m_axi_result_AWID),
    .I_AWLEN(relu_bn8_U0_m_axi_result_AWLEN),
    .I_AWSIZE(relu_bn8_U0_m_axi_result_AWSIZE),
    .I_AWLOCK(relu_bn8_U0_m_axi_result_AWLOCK),
    .I_AWCACHE(relu_bn8_U0_m_axi_result_AWCACHE),
    .I_AWQOS(relu_bn8_U0_m_axi_result_AWQOS),
    .I_AWPROT(relu_bn8_U0_m_axi_result_AWPROT),
    .I_AWUSER(relu_bn8_U0_m_axi_result_AWUSER),
    .I_AWBURST(relu_bn8_U0_m_axi_result_AWBURST),
    .I_AWREGION(relu_bn8_U0_m_axi_result_AWREGION),
    .I_WVALID(relu_bn8_U0_m_axi_result_WVALID),
    .I_WREADY(gmem_WREADY),
    .I_WDATA(relu_bn8_U0_m_axi_result_WDATA),
    .I_WID(relu_bn8_U0_m_axi_result_WID),
    .I_WUSER(relu_bn8_U0_m_axi_result_WUSER),
    .I_WLAST(relu_bn8_U0_m_axi_result_WLAST),
    .I_WSTRB(relu_bn8_U0_m_axi_result_WSTRB),
    .I_BVALID(gmem_BVALID),
    .I_BREADY(relu_bn8_U0_m_axi_result_BREADY),
    .I_BRESP(gmem_BRESP),
    .I_BID(gmem_BID),
    .I_BUSER(gmem_BUSER)
);

conv113 conv113_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(conv113_U0_ap_start),
    .start_full_n(conv113_U0_start_full_n),
    .ap_done(conv113_U0_ap_done),
    .ap_continue(conv113_U0_ap_continue),
    .ap_idle(conv113_U0_ap_idle),
    .ap_ready(conv113_U0_ap_ready),
    .start_out(conv113_U0_start_out),
    .start_write(conv113_U0_start_write),
    .m_axi_input_image_AWVALID(conv113_U0_m_axi_input_image_AWVALID),
    .m_axi_input_image_AWREADY(1'b0),
    .m_axi_input_image_AWADDR(conv113_U0_m_axi_input_image_AWADDR),
    .m_axi_input_image_AWID(conv113_U0_m_axi_input_image_AWID),
    .m_axi_input_image_AWLEN(conv113_U0_m_axi_input_image_AWLEN),
    .m_axi_input_image_AWSIZE(conv113_U0_m_axi_input_image_AWSIZE),
    .m_axi_input_image_AWBURST(conv113_U0_m_axi_input_image_AWBURST),
    .m_axi_input_image_AWLOCK(conv113_U0_m_axi_input_image_AWLOCK),
    .m_axi_input_image_AWCACHE(conv113_U0_m_axi_input_image_AWCACHE),
    .m_axi_input_image_AWPROT(conv113_U0_m_axi_input_image_AWPROT),
    .m_axi_input_image_AWQOS(conv113_U0_m_axi_input_image_AWQOS),
    .m_axi_input_image_AWREGION(conv113_U0_m_axi_input_image_AWREGION),
    .m_axi_input_image_AWUSER(conv113_U0_m_axi_input_image_AWUSER),
    .m_axi_input_image_WVALID(conv113_U0_m_axi_input_image_WVALID),
    .m_axi_input_image_WREADY(1'b0),
    .m_axi_input_image_WDATA(conv113_U0_m_axi_input_image_WDATA),
    .m_axi_input_image_WSTRB(conv113_U0_m_axi_input_image_WSTRB),
    .m_axi_input_image_WLAST(conv113_U0_m_axi_input_image_WLAST),
    .m_axi_input_image_WID(conv113_U0_m_axi_input_image_WID),
    .m_axi_input_image_WUSER(conv113_U0_m_axi_input_image_WUSER),
    .m_axi_input_image_ARVALID(conv113_U0_m_axi_input_image_ARVALID),
    .m_axi_input_image_ARREADY(gmem_ARREADY),
    .m_axi_input_image_ARADDR(conv113_U0_m_axi_input_image_ARADDR),
    .m_axi_input_image_ARID(conv113_U0_m_axi_input_image_ARID),
    .m_axi_input_image_ARLEN(conv113_U0_m_axi_input_image_ARLEN),
    .m_axi_input_image_ARSIZE(conv113_U0_m_axi_input_image_ARSIZE),
    .m_axi_input_image_ARBURST(conv113_U0_m_axi_input_image_ARBURST),
    .m_axi_input_image_ARLOCK(conv113_U0_m_axi_input_image_ARLOCK),
    .m_axi_input_image_ARCACHE(conv113_U0_m_axi_input_image_ARCACHE),
    .m_axi_input_image_ARPROT(conv113_U0_m_axi_input_image_ARPROT),
    .m_axi_input_image_ARQOS(conv113_U0_m_axi_input_image_ARQOS),
    .m_axi_input_image_ARREGION(conv113_U0_m_axi_input_image_ARREGION),
    .m_axi_input_image_ARUSER(conv113_U0_m_axi_input_image_ARUSER),
    .m_axi_input_image_RVALID(gmem_RVALID),
    .m_axi_input_image_RREADY(conv113_U0_m_axi_input_image_RREADY),
    .m_axi_input_image_RDATA(gmem_RDATA),
    .m_axi_input_image_RLAST(gmem_RLAST),
    .m_axi_input_image_RID(gmem_RID),
    .m_axi_input_image_RUSER(gmem_RUSER),
    .m_axi_input_image_RRESP(gmem_RRESP),
    .m_axi_input_image_BVALID(1'b0),
    .m_axi_input_image_BREADY(conv113_U0_m_axi_input_image_BREADY),
    .m_axi_input_image_BRESP(2'd0),
    .m_axi_input_image_BID(1'd0),
    .m_axi_input_image_BUSER(1'd0),
    .input_image_offset(input_image),
    .conv1_pipe_1_V_V_din(conv113_U0_conv1_pipe_1_V_V_din),
    .conv1_pipe_1_V_V_full_n(conv1_pipe_1_V_V_full_n),
    .conv1_pipe_1_V_V_write(conv113_U0_conv1_pipe_1_V_V_write),
    .result(result),
    .result_out_din(conv113_U0_result_out_din),
    .result_out_full_n(result_c_full_n),
    .result_out_write(conv113_U0_result_out_write)
);

relu_bn1 relu_bn1_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(relu_bn1_U0_ap_start),
    .start_full_n(start_for_maxpool1_U0_full_n),
    .ap_done(relu_bn1_U0_ap_done),
    .ap_continue(relu_bn1_U0_ap_continue),
    .ap_idle(relu_bn1_U0_ap_idle),
    .ap_ready(relu_bn1_U0_ap_ready),
    .start_out(relu_bn1_U0_start_out),
    .start_write(relu_bn1_U0_start_write),
    .conv1_pipe_1_V_V_dout(conv1_pipe_1_V_V_dout),
    .conv1_pipe_1_V_V_empty_n(conv1_pipe_1_V_V_empty_n),
    .conv1_pipe_1_V_V_read(relu_bn1_U0_conv1_pipe_1_V_V_read),
    .relu1_pipe_2_V_V_din(relu_bn1_U0_relu1_pipe_2_V_V_din),
    .relu1_pipe_2_V_V_full_n(relu1_pipe_2_V_V_full_n),
    .relu1_pipe_2_V_V_write(relu_bn1_U0_relu1_pipe_2_V_V_write)
);

maxpool1 maxpool1_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(maxpool1_U0_ap_start),
    .start_full_n(start_for_conv2_U0_full_n),
    .ap_done(maxpool1_U0_ap_done),
    .ap_continue(maxpool1_U0_ap_continue),
    .ap_idle(maxpool1_U0_ap_idle),
    .ap_ready(maxpool1_U0_ap_ready),
    .start_out(maxpool1_U0_start_out),
    .start_write(maxpool1_U0_start_write),
    .relu1_pipe_2_V_V_dout(relu1_pipe_2_V_V_dout),
    .relu1_pipe_2_V_V_empty_n(relu1_pipe_2_V_V_empty_n),
    .relu1_pipe_2_V_V_read(maxpool1_U0_relu1_pipe_2_V_V_read),
    .pool1_pipe_2_V_V_din(maxpool1_U0_pool1_pipe_2_V_V_din),
    .pool1_pipe_2_V_V_full_n(pool1_pipe_2_V_V_full_n),
    .pool1_pipe_2_V_V_write(maxpool1_U0_pool1_pipe_2_V_V_write)
);

conv2 conv2_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(conv2_U0_ap_start),
    .start_full_n(start_for_relu_bn2_U0_full_n),
    .ap_done(conv2_U0_ap_done),
    .ap_continue(conv2_U0_ap_continue),
    .ap_idle(conv2_U0_ap_idle),
    .ap_ready(conv2_U0_ap_ready),
    .start_out(conv2_U0_start_out),
    .start_write(conv2_U0_start_write),
    .pool1_pipe_2_V_V_dout(pool1_pipe_2_V_V_dout),
    .pool1_pipe_2_V_V_empty_n(pool1_pipe_2_V_V_empty_n),
    .pool1_pipe_2_V_V_read(conv2_U0_pool1_pipe_2_V_V_read),
    .conv2_pipe_3_V_V_din(conv2_U0_conv2_pipe_3_V_V_din),
    .conv2_pipe_3_V_V_full_n(conv2_pipe_3_V_V_full_n),
    .conv2_pipe_3_V_V_write(conv2_U0_conv2_pipe_3_V_V_write)
);

relu_bn2 relu_bn2_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(relu_bn2_U0_ap_start),
    .start_full_n(start_for_maxpool2_U0_full_n),
    .ap_done(relu_bn2_U0_ap_done),
    .ap_continue(relu_bn2_U0_ap_continue),
    .ap_idle(relu_bn2_U0_ap_idle),
    .ap_ready(relu_bn2_U0_ap_ready),
    .start_out(relu_bn2_U0_start_out),
    .start_write(relu_bn2_U0_start_write),
    .conv2_pipe_3_V_V_dout(conv2_pipe_3_V_V_dout),
    .conv2_pipe_3_V_V_empty_n(conv2_pipe_3_V_V_empty_n),
    .conv2_pipe_3_V_V_read(relu_bn2_U0_conv2_pipe_3_V_V_read),
    .relu2_pipe_4_V_V_din(relu_bn2_U0_relu2_pipe_4_V_V_din),
    .relu2_pipe_4_V_V_full_n(relu2_pipe_4_V_V_full_n),
    .relu2_pipe_4_V_V_write(relu_bn2_U0_relu2_pipe_4_V_V_write)
);

maxpool2 maxpool2_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(maxpool2_U0_ap_start),
    .start_full_n(start_for_conv3_U0_full_n),
    .ap_done(maxpool2_U0_ap_done),
    .ap_continue(maxpool2_U0_ap_continue),
    .ap_idle(maxpool2_U0_ap_idle),
    .ap_ready(maxpool2_U0_ap_ready),
    .start_out(maxpool2_U0_start_out),
    .start_write(maxpool2_U0_start_write),
    .relu2_pipe_4_V_V_dout(relu2_pipe_4_V_V_dout),
    .relu2_pipe_4_V_V_empty_n(relu2_pipe_4_V_V_empty_n),
    .relu2_pipe_4_V_V_read(maxpool2_U0_relu2_pipe_4_V_V_read),
    .pool2_pipe_4_V_V_din(maxpool2_U0_pool2_pipe_4_V_V_din),
    .pool2_pipe_4_V_V_full_n(pool2_pipe_4_V_V_full_n),
    .pool2_pipe_4_V_V_write(maxpool2_U0_pool2_pipe_4_V_V_write)
);

conv3 conv3_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(conv3_U0_ap_start),
    .start_full_n(start_for_relu_bn3_U0_full_n),
    .ap_done(conv3_U0_ap_done),
    .ap_continue(conv3_U0_ap_continue),
    .ap_idle(conv3_U0_ap_idle),
    .ap_ready(conv3_U0_ap_ready),
    .start_out(conv3_U0_start_out),
    .start_write(conv3_U0_start_write),
    .pool2_pipe_4_V_V_dout(pool2_pipe_4_V_V_dout),
    .pool2_pipe_4_V_V_empty_n(pool2_pipe_4_V_V_empty_n),
    .pool2_pipe_4_V_V_read(conv3_U0_pool2_pipe_4_V_V_read),
    .conv3_pipe_5_V_V_din(conv3_U0_conv3_pipe_5_V_V_din),
    .conv3_pipe_5_V_V_full_n(conv3_pipe_5_V_V_full_n),
    .conv3_pipe_5_V_V_write(conv3_U0_conv3_pipe_5_V_V_write)
);

relu_bn3 relu_bn3_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(relu_bn3_U0_ap_start),
    .start_full_n(start_for_maxpool3_U0_full_n),
    .ap_done(relu_bn3_U0_ap_done),
    .ap_continue(relu_bn3_U0_ap_continue),
    .ap_idle(relu_bn3_U0_ap_idle),
    .ap_ready(relu_bn3_U0_ap_ready),
    .start_out(relu_bn3_U0_start_out),
    .start_write(relu_bn3_U0_start_write),
    .conv3_pipe_5_V_V_dout(conv3_pipe_5_V_V_dout),
    .conv3_pipe_5_V_V_empty_n(conv3_pipe_5_V_V_empty_n),
    .conv3_pipe_5_V_V_read(relu_bn3_U0_conv3_pipe_5_V_V_read),
    .relu3_pipe_6_V_V_din(relu_bn3_U0_relu3_pipe_6_V_V_din),
    .relu3_pipe_6_V_V_full_n(relu3_pipe_6_V_V_full_n),
    .relu3_pipe_6_V_V_write(relu_bn3_U0_relu3_pipe_6_V_V_write)
);

maxpool3 maxpool3_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(maxpool3_U0_ap_start),
    .start_full_n(start_for_conv4_U0_full_n),
    .ap_done(maxpool3_U0_ap_done),
    .ap_continue(maxpool3_U0_ap_continue),
    .ap_idle(maxpool3_U0_ap_idle),
    .ap_ready(maxpool3_U0_ap_ready),
    .start_out(maxpool3_U0_start_out),
    .start_write(maxpool3_U0_start_write),
    .relu3_pipe_6_V_V_dout(relu3_pipe_6_V_V_dout),
    .relu3_pipe_6_V_V_empty_n(relu3_pipe_6_V_V_empty_n),
    .relu3_pipe_6_V_V_read(maxpool3_U0_relu3_pipe_6_V_V_read),
    .pool3_pipe_6_V_V_din(maxpool3_U0_pool3_pipe_6_V_V_din),
    .pool3_pipe_6_V_V_full_n(pool3_pipe_6_V_V_full_n),
    .pool3_pipe_6_V_V_write(maxpool3_U0_pool3_pipe_6_V_V_write)
);

conv4 conv4_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(conv4_U0_ap_start),
    .start_full_n(start_for_relu_bn4_U0_full_n),
    .ap_done(conv4_U0_ap_done),
    .ap_continue(conv4_U0_ap_continue),
    .ap_idle(conv4_U0_ap_idle),
    .ap_ready(conv4_U0_ap_ready),
    .start_out(conv4_U0_start_out),
    .start_write(conv4_U0_start_write),
    .pool3_pipe_6_V_V_dout(pool3_pipe_6_V_V_dout),
    .pool3_pipe_6_V_V_empty_n(pool3_pipe_6_V_V_empty_n),
    .pool3_pipe_6_V_V_read(conv4_U0_pool3_pipe_6_V_V_read),
    .conv4_pipe_7_V_V_din(conv4_U0_conv4_pipe_7_V_V_din),
    .conv4_pipe_7_V_V_full_n(conv4_pipe_7_V_V_full_n),
    .conv4_pipe_7_V_V_write(conv4_U0_conv4_pipe_7_V_V_write)
);

relu_bn4 relu_bn4_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(relu_bn4_U0_ap_start),
    .start_full_n(start_for_maxpool4_U0_full_n),
    .ap_done(relu_bn4_U0_ap_done),
    .ap_continue(relu_bn4_U0_ap_continue),
    .ap_idle(relu_bn4_U0_ap_idle),
    .ap_ready(relu_bn4_U0_ap_ready),
    .start_out(relu_bn4_U0_start_out),
    .start_write(relu_bn4_U0_start_write),
    .conv4_pipe_7_V_V_dout(conv4_pipe_7_V_V_dout),
    .conv4_pipe_7_V_V_empty_n(conv4_pipe_7_V_V_empty_n),
    .conv4_pipe_7_V_V_read(relu_bn4_U0_conv4_pipe_7_V_V_read),
    .relu4_pipe_8_V_V_din(relu_bn4_U0_relu4_pipe_8_V_V_din),
    .relu4_pipe_8_V_V_full_n(relu4_pipe_8_V_V_full_n),
    .relu4_pipe_8_V_V_write(relu_bn4_U0_relu4_pipe_8_V_V_write)
);

maxpool4 maxpool4_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(maxpool4_U0_ap_start),
    .start_full_n(start_for_conv5_U0_full_n),
    .ap_done(maxpool4_U0_ap_done),
    .ap_continue(maxpool4_U0_ap_continue),
    .ap_idle(maxpool4_U0_ap_idle),
    .ap_ready(maxpool4_U0_ap_ready),
    .start_out(maxpool4_U0_start_out),
    .start_write(maxpool4_U0_start_write),
    .relu4_pipe_8_V_V_dout(relu4_pipe_8_V_V_dout),
    .relu4_pipe_8_V_V_empty_n(relu4_pipe_8_V_V_empty_n),
    .relu4_pipe_8_V_V_read(maxpool4_U0_relu4_pipe_8_V_V_read),
    .pool4_pipe_8_V_V_din(maxpool4_U0_pool4_pipe_8_V_V_din),
    .pool4_pipe_8_V_V_full_n(pool4_pipe_8_V_V_full_n),
    .pool4_pipe_8_V_V_write(maxpool4_U0_pool4_pipe_8_V_V_write)
);

conv5 conv5_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(conv5_U0_ap_start),
    .start_full_n(start_for_relu_bn5_U0_full_n),
    .ap_done(conv5_U0_ap_done),
    .ap_continue(conv5_U0_ap_continue),
    .ap_idle(conv5_U0_ap_idle),
    .ap_ready(conv5_U0_ap_ready),
    .start_out(conv5_U0_start_out),
    .start_write(conv5_U0_start_write),
    .pool4_pipe_8_V_V_dout(pool4_pipe_8_V_V_dout),
    .pool4_pipe_8_V_V_empty_n(pool4_pipe_8_V_V_empty_n),
    .pool4_pipe_8_V_V_read(conv5_U0_pool4_pipe_8_V_V_read),
    .conv5_pipe_9_V_V_din(conv5_U0_conv5_pipe_9_V_V_din),
    .conv5_pipe_9_V_V_full_n(conv5_pipe_9_V_V_full_n),
    .conv5_pipe_9_V_V_write(conv5_U0_conv5_pipe_9_V_V_write)
);

relu_bn5 relu_bn5_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(relu_bn5_U0_ap_start),
    .start_full_n(start_for_conv6_U0_full_n),
    .ap_done(relu_bn5_U0_ap_done),
    .ap_continue(relu_bn5_U0_ap_continue),
    .ap_idle(relu_bn5_U0_ap_idle),
    .ap_ready(relu_bn5_U0_ap_ready),
    .start_out(relu_bn5_U0_start_out),
    .start_write(relu_bn5_U0_start_write),
    .conv5_pipe_9_V_V_dout(conv5_pipe_9_V_V_dout),
    .conv5_pipe_9_V_V_empty_n(conv5_pipe_9_V_V_empty_n),
    .conv5_pipe_9_V_V_read(relu_bn5_U0_conv5_pipe_9_V_V_read),
    .relu5_pipe_10_V_V_din(relu_bn5_U0_relu5_pipe_10_V_V_din),
    .relu5_pipe_10_V_V_full_n(relu5_pipe_10_V_V_full_n),
    .relu5_pipe_10_V_V_write(relu_bn5_U0_relu5_pipe_10_V_V_write)
);

conv6 conv6_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(conv6_U0_ap_start),
    .start_full_n(start_for_relu_bn6_U0_full_n),
    .ap_done(conv6_U0_ap_done),
    .ap_continue(conv6_U0_ap_continue),
    .ap_idle(conv6_U0_ap_idle),
    .ap_ready(conv6_U0_ap_ready),
    .start_out(conv6_U0_start_out),
    .start_write(conv6_U0_start_write),
    .relu5_pipe_10_V_V_dout(relu5_pipe_10_V_V_dout),
    .relu5_pipe_10_V_V_empty_n(relu5_pipe_10_V_V_empty_n),
    .relu5_pipe_10_V_V_read(conv6_U0_relu5_pipe_10_V_V_read),
    .conv6_pipe_11_V_V_din(conv6_U0_conv6_pipe_11_V_V_din),
    .conv6_pipe_11_V_V_full_n(conv6_pipe_11_V_V_full_n),
    .conv6_pipe_11_V_V_write(conv6_U0_conv6_pipe_11_V_V_write)
);

relu_bn6 relu_bn6_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(relu_bn6_U0_ap_start),
    .start_full_n(start_for_conv7_U0_full_n),
    .ap_done(relu_bn6_U0_ap_done),
    .ap_continue(relu_bn6_U0_ap_continue),
    .ap_idle(relu_bn6_U0_ap_idle),
    .ap_ready(relu_bn6_U0_ap_ready),
    .start_out(relu_bn6_U0_start_out),
    .start_write(relu_bn6_U0_start_write),
    .conv6_pipe_11_V_V_dout(conv6_pipe_11_V_V_dout),
    .conv6_pipe_11_V_V_empty_n(conv6_pipe_11_V_V_empty_n),
    .conv6_pipe_11_V_V_read(relu_bn6_U0_conv6_pipe_11_V_V_read),
    .relu6_pipe_12_V_V_din(relu_bn6_U0_relu6_pipe_12_V_V_din),
    .relu6_pipe_12_V_V_full_n(relu6_pipe_12_V_V_full_n),
    .relu6_pipe_12_V_V_write(relu_bn6_U0_relu6_pipe_12_V_V_write)
);

conv7 conv7_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(conv7_U0_ap_start),
    .start_full_n(start_for_relu_bn7_U0_full_n),
    .ap_done(conv7_U0_ap_done),
    .ap_continue(conv7_U0_ap_continue),
    .ap_idle(conv7_U0_ap_idle),
    .ap_ready(conv7_U0_ap_ready),
    .start_out(conv7_U0_start_out),
    .start_write(conv7_U0_start_write),
    .relu6_pipe_12_V_V_dout(relu6_pipe_12_V_V_dout),
    .relu6_pipe_12_V_V_empty_n(relu6_pipe_12_V_V_empty_n),
    .relu6_pipe_12_V_V_read(conv7_U0_relu6_pipe_12_V_V_read),
    .conv7_pipe_13_V_V_din(conv7_U0_conv7_pipe_13_V_V_din),
    .conv7_pipe_13_V_V_full_n(conv7_pipe_13_V_V_full_n),
    .conv7_pipe_13_V_V_write(conv7_U0_conv7_pipe_13_V_V_write)
);

relu_bn7 relu_bn7_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(relu_bn7_U0_ap_start),
    .start_full_n(start_for_conv8_U0_full_n),
    .ap_done(relu_bn7_U0_ap_done),
    .ap_continue(relu_bn7_U0_ap_continue),
    .ap_idle(relu_bn7_U0_ap_idle),
    .ap_ready(relu_bn7_U0_ap_ready),
    .start_out(relu_bn7_U0_start_out),
    .start_write(relu_bn7_U0_start_write),
    .conv7_pipe_13_V_V_dout(conv7_pipe_13_V_V_dout),
    .conv7_pipe_13_V_V_empty_n(conv7_pipe_13_V_V_empty_n),
    .conv7_pipe_13_V_V_read(relu_bn7_U0_conv7_pipe_13_V_V_read),
    .relu7_pipe_14_V_V_din(relu_bn7_U0_relu7_pipe_14_V_V_din),
    .relu7_pipe_14_V_V_full_n(relu7_pipe_14_V_V_full_n),
    .relu7_pipe_14_V_V_write(relu_bn7_U0_relu7_pipe_14_V_V_write)
);

conv8 conv8_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(conv8_U0_ap_start),
    .ap_done(conv8_U0_ap_done),
    .ap_continue(conv8_U0_ap_continue),
    .ap_idle(conv8_U0_ap_idle),
    .ap_ready(conv8_U0_ap_ready),
    .relu7_pipe_14_V_V_dout(relu7_pipe_14_V_V_dout),
    .relu7_pipe_14_V_V_empty_n(relu7_pipe_14_V_V_empty_n),
    .relu7_pipe_14_V_V_read(conv8_U0_relu7_pipe_14_V_V_read),
    .conv8_pipe_15_V_V_din(conv8_U0_conv8_pipe_15_V_V_din),
    .conv8_pipe_15_V_V_full_n(conv8_pipe_15_V_V_full_n),
    .conv8_pipe_15_V_V_write(conv8_U0_conv8_pipe_15_V_V_write)
);

relu_bn8 relu_bn8_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(relu_bn8_U0_ap_start),
    .ap_done(relu_bn8_U0_ap_done),
    .ap_continue(relu_bn8_U0_ap_continue),
    .ap_idle(relu_bn8_U0_ap_idle),
    .ap_ready(relu_bn8_U0_ap_ready),
    .conv8_pipe_15_V_V_dout(conv8_pipe_15_V_V_dout),
    .conv8_pipe_15_V_V_empty_n(conv8_pipe_15_V_V_empty_n),
    .conv8_pipe_15_V_V_read(relu_bn8_U0_conv8_pipe_15_V_V_read),
    .m_axi_result_AWVALID(relu_bn8_U0_m_axi_result_AWVALID),
    .m_axi_result_AWREADY(gmem_AWREADY),
    .m_axi_result_AWADDR(relu_bn8_U0_m_axi_result_AWADDR),
    .m_axi_result_AWID(relu_bn8_U0_m_axi_result_AWID),
    .m_axi_result_AWLEN(relu_bn8_U0_m_axi_result_AWLEN),
    .m_axi_result_AWSIZE(relu_bn8_U0_m_axi_result_AWSIZE),
    .m_axi_result_AWBURST(relu_bn8_U0_m_axi_result_AWBURST),
    .m_axi_result_AWLOCK(relu_bn8_U0_m_axi_result_AWLOCK),
    .m_axi_result_AWCACHE(relu_bn8_U0_m_axi_result_AWCACHE),
    .m_axi_result_AWPROT(relu_bn8_U0_m_axi_result_AWPROT),
    .m_axi_result_AWQOS(relu_bn8_U0_m_axi_result_AWQOS),
    .m_axi_result_AWREGION(relu_bn8_U0_m_axi_result_AWREGION),
    .m_axi_result_AWUSER(relu_bn8_U0_m_axi_result_AWUSER),
    .m_axi_result_WVALID(relu_bn8_U0_m_axi_result_WVALID),
    .m_axi_result_WREADY(gmem_WREADY),
    .m_axi_result_WDATA(relu_bn8_U0_m_axi_result_WDATA),
    .m_axi_result_WSTRB(relu_bn8_U0_m_axi_result_WSTRB),
    .m_axi_result_WLAST(relu_bn8_U0_m_axi_result_WLAST),
    .m_axi_result_WID(relu_bn8_U0_m_axi_result_WID),
    .m_axi_result_WUSER(relu_bn8_U0_m_axi_result_WUSER),
    .m_axi_result_ARVALID(relu_bn8_U0_m_axi_result_ARVALID),
    .m_axi_result_ARREADY(1'b0),
    .m_axi_result_ARADDR(relu_bn8_U0_m_axi_result_ARADDR),
    .m_axi_result_ARID(relu_bn8_U0_m_axi_result_ARID),
    .m_axi_result_ARLEN(relu_bn8_U0_m_axi_result_ARLEN),
    .m_axi_result_ARSIZE(relu_bn8_U0_m_axi_result_ARSIZE),
    .m_axi_result_ARBURST(relu_bn8_U0_m_axi_result_ARBURST),
    .m_axi_result_ARLOCK(relu_bn8_U0_m_axi_result_ARLOCK),
    .m_axi_result_ARCACHE(relu_bn8_U0_m_axi_result_ARCACHE),
    .m_axi_result_ARPROT(relu_bn8_U0_m_axi_result_ARPROT),
    .m_axi_result_ARQOS(relu_bn8_U0_m_axi_result_ARQOS),
    .m_axi_result_ARREGION(relu_bn8_U0_m_axi_result_ARREGION),
    .m_axi_result_ARUSER(relu_bn8_U0_m_axi_result_ARUSER),
    .m_axi_result_RVALID(1'b0),
    .m_axi_result_RREADY(relu_bn8_U0_m_axi_result_RREADY),
    .m_axi_result_RDATA(32'd0),
    .m_axi_result_RLAST(1'b0),
    .m_axi_result_RID(1'd0),
    .m_axi_result_RUSER(1'd0),
    .m_axi_result_RRESP(2'd0),
    .m_axi_result_BVALID(gmem_BVALID),
    .m_axi_result_BREADY(relu_bn8_U0_m_axi_result_BREADY),
    .m_axi_result_BRESP(gmem_BRESP),
    .m_axi_result_BID(gmem_BID),
    .m_axi_result_BUSER(gmem_BUSER),
    .result_offset_dout(result_c_dout),
    .result_offset_empty_n(result_c_empty_n),
    .result_offset_read(relu_bn8_U0_result_offset_read)
);

fifo_w16_d128_A conv1_pipe_1_V_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(conv113_U0_conv1_pipe_1_V_V_din),
    .if_full_n(conv1_pipe_1_V_V_full_n),
    .if_write(conv113_U0_conv1_pipe_1_V_V_write),
    .if_dout(conv1_pipe_1_V_V_dout),
    .if_empty_n(conv1_pipe_1_V_V_empty_n),
    .if_read(relu_bn1_U0_conv1_pipe_1_V_V_read)
);

fifo_w32_d20_A result_c_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(conv113_U0_result_out_din),
    .if_full_n(result_c_full_n),
    .if_write(conv113_U0_result_out_write),
    .if_dout(result_c_dout),
    .if_empty_n(result_c_empty_n),
    .if_read(relu_bn8_U0_result_offset_read)
);

fifo_w5_d128_A relu1_pipe_2_V_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(relu_bn1_U0_relu1_pipe_2_V_V_din),
    .if_full_n(relu1_pipe_2_V_V_full_n),
    .if_write(relu_bn1_U0_relu1_pipe_2_V_V_write),
    .if_dout(relu1_pipe_2_V_V_dout),
    .if_empty_n(relu1_pipe_2_V_V_empty_n),
    .if_read(maxpool1_U0_relu1_pipe_2_V_V_read)
);

fifo_w5_d128_A pool1_pipe_2_V_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(maxpool1_U0_pool1_pipe_2_V_V_din),
    .if_full_n(pool1_pipe_2_V_V_full_n),
    .if_write(maxpool1_U0_pool1_pipe_2_V_V_write),
    .if_dout(pool1_pipe_2_V_V_dout),
    .if_empty_n(pool1_pipe_2_V_V_empty_n),
    .if_read(conv2_U0_pool1_pipe_2_V_V_read)
);

fifo_w16_d128_A conv2_pipe_3_V_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(conv2_U0_conv2_pipe_3_V_V_din),
    .if_full_n(conv2_pipe_3_V_V_full_n),
    .if_write(conv2_U0_conv2_pipe_3_V_V_write),
    .if_dout(conv2_pipe_3_V_V_dout),
    .if_empty_n(conv2_pipe_3_V_V_empty_n),
    .if_read(relu_bn2_U0_conv2_pipe_3_V_V_read)
);

fifo_w5_d128_A relu2_pipe_4_V_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(relu_bn2_U0_relu2_pipe_4_V_V_din),
    .if_full_n(relu2_pipe_4_V_V_full_n),
    .if_write(relu_bn2_U0_relu2_pipe_4_V_V_write),
    .if_dout(relu2_pipe_4_V_V_dout),
    .if_empty_n(relu2_pipe_4_V_V_empty_n),
    .if_read(maxpool2_U0_relu2_pipe_4_V_V_read)
);

fifo_w5_d128_A pool2_pipe_4_V_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(maxpool2_U0_pool2_pipe_4_V_V_din),
    .if_full_n(pool2_pipe_4_V_V_full_n),
    .if_write(maxpool2_U0_pool2_pipe_4_V_V_write),
    .if_dout(pool2_pipe_4_V_V_dout),
    .if_empty_n(pool2_pipe_4_V_V_empty_n),
    .if_read(conv3_U0_pool2_pipe_4_V_V_read)
);

fifo_w16_d128_A conv3_pipe_5_V_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(conv3_U0_conv3_pipe_5_V_V_din),
    .if_full_n(conv3_pipe_5_V_V_full_n),
    .if_write(conv3_U0_conv3_pipe_5_V_V_write),
    .if_dout(conv3_pipe_5_V_V_dout),
    .if_empty_n(conv3_pipe_5_V_V_empty_n),
    .if_read(relu_bn3_U0_conv3_pipe_5_V_V_read)
);

fifo_w5_d128_A relu3_pipe_6_V_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(relu_bn3_U0_relu3_pipe_6_V_V_din),
    .if_full_n(relu3_pipe_6_V_V_full_n),
    .if_write(relu_bn3_U0_relu3_pipe_6_V_V_write),
    .if_dout(relu3_pipe_6_V_V_dout),
    .if_empty_n(relu3_pipe_6_V_V_empty_n),
    .if_read(maxpool3_U0_relu3_pipe_6_V_V_read)
);

fifo_w5_d128_A pool3_pipe_6_V_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(maxpool3_U0_pool3_pipe_6_V_V_din),
    .if_full_n(pool3_pipe_6_V_V_full_n),
    .if_write(maxpool3_U0_pool3_pipe_6_V_V_write),
    .if_dout(pool3_pipe_6_V_V_dout),
    .if_empty_n(pool3_pipe_6_V_V_empty_n),
    .if_read(conv4_U0_pool3_pipe_6_V_V_read)
);

fifo_w16_d128_A conv4_pipe_7_V_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(conv4_U0_conv4_pipe_7_V_V_din),
    .if_full_n(conv4_pipe_7_V_V_full_n),
    .if_write(conv4_U0_conv4_pipe_7_V_V_write),
    .if_dout(conv4_pipe_7_V_V_dout),
    .if_empty_n(conv4_pipe_7_V_V_empty_n),
    .if_read(relu_bn4_U0_conv4_pipe_7_V_V_read)
);

fifo_w5_d128_A relu4_pipe_8_V_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(relu_bn4_U0_relu4_pipe_8_V_V_din),
    .if_full_n(relu4_pipe_8_V_V_full_n),
    .if_write(relu_bn4_U0_relu4_pipe_8_V_V_write),
    .if_dout(relu4_pipe_8_V_V_dout),
    .if_empty_n(relu4_pipe_8_V_V_empty_n),
    .if_read(maxpool4_U0_relu4_pipe_8_V_V_read)
);

fifo_w5_d128_A pool4_pipe_8_V_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(maxpool4_U0_pool4_pipe_8_V_V_din),
    .if_full_n(pool4_pipe_8_V_V_full_n),
    .if_write(maxpool4_U0_pool4_pipe_8_V_V_write),
    .if_dout(pool4_pipe_8_V_V_dout),
    .if_empty_n(pool4_pipe_8_V_V_empty_n),
    .if_read(conv5_U0_pool4_pipe_8_V_V_read)
);

fifo_w16_d128_A conv5_pipe_9_V_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(conv5_U0_conv5_pipe_9_V_V_din),
    .if_full_n(conv5_pipe_9_V_V_full_n),
    .if_write(conv5_U0_conv5_pipe_9_V_V_write),
    .if_dout(conv5_pipe_9_V_V_dout),
    .if_empty_n(conv5_pipe_9_V_V_empty_n),
    .if_read(relu_bn5_U0_conv5_pipe_9_V_V_read)
);

fifo_w5_d128_A relu5_pipe_10_V_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(relu_bn5_U0_relu5_pipe_10_V_V_din),
    .if_full_n(relu5_pipe_10_V_V_full_n),
    .if_write(relu_bn5_U0_relu5_pipe_10_V_V_write),
    .if_dout(relu5_pipe_10_V_V_dout),
    .if_empty_n(relu5_pipe_10_V_V_empty_n),
    .if_read(conv6_U0_relu5_pipe_10_V_V_read)
);

fifo_w16_d128_A conv6_pipe_11_V_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(conv6_U0_conv6_pipe_11_V_V_din),
    .if_full_n(conv6_pipe_11_V_V_full_n),
    .if_write(conv6_U0_conv6_pipe_11_V_V_write),
    .if_dout(conv6_pipe_11_V_V_dout),
    .if_empty_n(conv6_pipe_11_V_V_empty_n),
    .if_read(relu_bn6_U0_conv6_pipe_11_V_V_read)
);

fifo_w5_d128_A relu6_pipe_12_V_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(relu_bn6_U0_relu6_pipe_12_V_V_din),
    .if_full_n(relu6_pipe_12_V_V_full_n),
    .if_write(relu_bn6_U0_relu6_pipe_12_V_V_write),
    .if_dout(relu6_pipe_12_V_V_dout),
    .if_empty_n(relu6_pipe_12_V_V_empty_n),
    .if_read(conv7_U0_relu6_pipe_12_V_V_read)
);

fifo_w16_d128_A conv7_pipe_13_V_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(conv7_U0_conv7_pipe_13_V_V_din),
    .if_full_n(conv7_pipe_13_V_V_full_n),
    .if_write(conv7_U0_conv7_pipe_13_V_V_write),
    .if_dout(conv7_pipe_13_V_V_dout),
    .if_empty_n(conv7_pipe_13_V_V_empty_n),
    .if_read(relu_bn7_U0_conv7_pipe_13_V_V_read)
);

fifo_w5_d128_A relu7_pipe_14_V_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(relu_bn7_U0_relu7_pipe_14_V_V_din),
    .if_full_n(relu7_pipe_14_V_V_full_n),
    .if_write(relu_bn7_U0_relu7_pipe_14_V_V_write),
    .if_dout(relu7_pipe_14_V_V_dout),
    .if_empty_n(relu7_pipe_14_V_V_empty_n),
    .if_read(conv8_U0_relu7_pipe_14_V_V_read)
);

fifo_w16_d128_A conv8_pipe_15_V_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(conv8_U0_conv8_pipe_15_V_V_din),
    .if_full_n(conv8_pipe_15_V_V_full_n),
    .if_write(conv8_U0_conv8_pipe_15_V_V_write),
    .if_dout(conv8_pipe_15_V_V_dout),
    .if_empty_n(conv8_pipe_15_V_V_empty_n),
    .if_read(relu_bn8_U0_conv8_pipe_15_V_V_read)
);

start_for_relu_bnCfe start_for_relu_bnCfe_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_relu_bn1_U0_din),
    .if_full_n(start_for_relu_bn1_U0_full_n),
    .if_write(conv113_U0_start_write),
    .if_dout(start_for_relu_bn1_U0_dout),
    .if_empty_n(start_for_relu_bn1_U0_empty_n),
    .if_read(relu_bn1_U0_ap_ready)
);

start_for_relu_bnCge start_for_relu_bnCge_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_relu_bn8_U0_din),
    .if_full_n(start_for_relu_bn8_U0_full_n),
    .if_write(conv113_U0_start_write),
    .if_dout(start_for_relu_bn8_U0_dout),
    .if_empty_n(start_for_relu_bn8_U0_empty_n),
    .if_read(relu_bn8_U0_ap_ready)
);

start_for_maxpoolChe start_for_maxpoolChe_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_maxpool1_U0_din),
    .if_full_n(start_for_maxpool1_U0_full_n),
    .if_write(relu_bn1_U0_start_write),
    .if_dout(start_for_maxpool1_U0_dout),
    .if_empty_n(start_for_maxpool1_U0_empty_n),
    .if_read(maxpool1_U0_ap_ready)
);

start_for_conv2_U0 start_for_conv2_U0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_conv2_U0_din),
    .if_full_n(start_for_conv2_U0_full_n),
    .if_write(maxpool1_U0_start_write),
    .if_dout(start_for_conv2_U0_dout),
    .if_empty_n(start_for_conv2_U0_empty_n),
    .if_read(conv2_U0_ap_ready)
);

start_for_relu_bnCie start_for_relu_bnCie_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_relu_bn2_U0_din),
    .if_full_n(start_for_relu_bn2_U0_full_n),
    .if_write(conv2_U0_start_write),
    .if_dout(start_for_relu_bn2_U0_dout),
    .if_empty_n(start_for_relu_bn2_U0_empty_n),
    .if_read(relu_bn2_U0_ap_ready)
);

start_for_maxpoolCje start_for_maxpoolCje_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_maxpool2_U0_din),
    .if_full_n(start_for_maxpool2_U0_full_n),
    .if_write(relu_bn2_U0_start_write),
    .if_dout(start_for_maxpool2_U0_dout),
    .if_empty_n(start_for_maxpool2_U0_empty_n),
    .if_read(maxpool2_U0_ap_ready)
);

start_for_conv3_U0 start_for_conv3_U0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_conv3_U0_din),
    .if_full_n(start_for_conv3_U0_full_n),
    .if_write(maxpool2_U0_start_write),
    .if_dout(start_for_conv3_U0_dout),
    .if_empty_n(start_for_conv3_U0_empty_n),
    .if_read(conv3_U0_ap_ready)
);

start_for_relu_bnCke start_for_relu_bnCke_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_relu_bn3_U0_din),
    .if_full_n(start_for_relu_bn3_U0_full_n),
    .if_write(conv3_U0_start_write),
    .if_dout(start_for_relu_bn3_U0_dout),
    .if_empty_n(start_for_relu_bn3_U0_empty_n),
    .if_read(relu_bn3_U0_ap_ready)
);

start_for_maxpoolCle start_for_maxpoolCle_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_maxpool3_U0_din),
    .if_full_n(start_for_maxpool3_U0_full_n),
    .if_write(relu_bn3_U0_start_write),
    .if_dout(start_for_maxpool3_U0_dout),
    .if_empty_n(start_for_maxpool3_U0_empty_n),
    .if_read(maxpool3_U0_ap_ready)
);

start_for_conv4_U0 start_for_conv4_U0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_conv4_U0_din),
    .if_full_n(start_for_conv4_U0_full_n),
    .if_write(maxpool3_U0_start_write),
    .if_dout(start_for_conv4_U0_dout),
    .if_empty_n(start_for_conv4_U0_empty_n),
    .if_read(conv4_U0_ap_ready)
);

start_for_relu_bnCme start_for_relu_bnCme_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_relu_bn4_U0_din),
    .if_full_n(start_for_relu_bn4_U0_full_n),
    .if_write(conv4_U0_start_write),
    .if_dout(start_for_relu_bn4_U0_dout),
    .if_empty_n(start_for_relu_bn4_U0_empty_n),
    .if_read(relu_bn4_U0_ap_ready)
);

start_for_maxpoolCne start_for_maxpoolCne_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_maxpool4_U0_din),
    .if_full_n(start_for_maxpool4_U0_full_n),
    .if_write(relu_bn4_U0_start_write),
    .if_dout(start_for_maxpool4_U0_dout),
    .if_empty_n(start_for_maxpool4_U0_empty_n),
    .if_read(maxpool4_U0_ap_ready)
);

start_for_conv5_U0 start_for_conv5_U0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_conv5_U0_din),
    .if_full_n(start_for_conv5_U0_full_n),
    .if_write(maxpool4_U0_start_write),
    .if_dout(start_for_conv5_U0_dout),
    .if_empty_n(start_for_conv5_U0_empty_n),
    .if_read(conv5_U0_ap_ready)
);

start_for_relu_bnCoe start_for_relu_bnCoe_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_relu_bn5_U0_din),
    .if_full_n(start_for_relu_bn5_U0_full_n),
    .if_write(conv5_U0_start_write),
    .if_dout(start_for_relu_bn5_U0_dout),
    .if_empty_n(start_for_relu_bn5_U0_empty_n),
    .if_read(relu_bn5_U0_ap_ready)
);

start_for_conv6_U0 start_for_conv6_U0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_conv6_U0_din),
    .if_full_n(start_for_conv6_U0_full_n),
    .if_write(relu_bn5_U0_start_write),
    .if_dout(start_for_conv6_U0_dout),
    .if_empty_n(start_for_conv6_U0_empty_n),
    .if_read(conv6_U0_ap_ready)
);

start_for_relu_bnCpe start_for_relu_bnCpe_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_relu_bn6_U0_din),
    .if_full_n(start_for_relu_bn6_U0_full_n),
    .if_write(conv6_U0_start_write),
    .if_dout(start_for_relu_bn6_U0_dout),
    .if_empty_n(start_for_relu_bn6_U0_empty_n),
    .if_read(relu_bn6_U0_ap_ready)
);

start_for_conv7_U0 start_for_conv7_U0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_conv7_U0_din),
    .if_full_n(start_for_conv7_U0_full_n),
    .if_write(relu_bn6_U0_start_write),
    .if_dout(start_for_conv7_U0_dout),
    .if_empty_n(start_for_conv7_U0_empty_n),
    .if_read(conv7_U0_ap_ready)
);

start_for_relu_bnCqe start_for_relu_bnCqe_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_relu_bn7_U0_din),
    .if_full_n(start_for_relu_bn7_U0_full_n),
    .if_write(conv7_U0_start_write),
    .if_dout(start_for_relu_bn7_U0_dout),
    .if_empty_n(start_for_relu_bn7_U0_empty_n),
    .if_read(relu_bn7_U0_ap_ready)
);

start_for_conv8_U0 start_for_conv8_U0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_conv8_U0_din),
    .if_full_n(start_for_conv8_U0_full_n),
    .if_write(relu_bn7_U0_start_write),
    .if_dout(start_for_conv8_U0_dout),
    .if_empty_n(start_for_conv8_U0_empty_n),
    .if_read(conv8_U0_ap_ready)
);

assign ap_done = relu_bn8_U0_ap_done;

assign ap_idle = (relu_bn8_U0_ap_idle & relu_bn7_U0_ap_idle & relu_bn6_U0_ap_idle & relu_bn5_U0_ap_idle & relu_bn4_U0_ap_idle & relu_bn3_U0_ap_idle & relu_bn2_U0_ap_idle & relu_bn1_U0_ap_idle & maxpool4_U0_ap_idle & maxpool3_U0_ap_idle & maxpool2_U0_ap_idle & maxpool1_U0_ap_idle & conv8_U0_ap_idle & conv7_U0_ap_idle & conv6_U0_ap_idle & conv5_U0_ap_idle & conv4_U0_ap_idle & conv3_U0_ap_idle & conv2_U0_ap_idle & conv113_U0_ap_idle);

assign ap_ready = conv113_U0_ap_ready;

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign ap_sync_continue = 1'b1;

assign ap_sync_done = relu_bn8_U0_ap_done;

assign ap_sync_ready = conv113_U0_ap_ready;

assign conv113_U0_ap_continue = 1'b1;

assign conv113_U0_ap_start = ap_start;

assign conv113_U0_start_full_n = (start_for_relu_bn8_U0_full_n & start_for_relu_bn1_U0_full_n);

assign conv2_U0_ap_continue = 1'b1;

assign conv2_U0_ap_start = start_for_conv2_U0_empty_n;

assign conv3_U0_ap_continue = 1'b1;

assign conv3_U0_ap_start = start_for_conv3_U0_empty_n;

assign conv4_U0_ap_continue = 1'b1;

assign conv4_U0_ap_start = start_for_conv4_U0_empty_n;

assign conv5_U0_ap_continue = 1'b1;

assign conv5_U0_ap_start = start_for_conv5_U0_empty_n;

assign conv6_U0_ap_continue = 1'b1;

assign conv6_U0_ap_start = start_for_conv6_U0_empty_n;

assign conv7_U0_ap_continue = 1'b1;

assign conv7_U0_ap_start = start_for_conv7_U0_empty_n;

assign conv8_U0_ap_continue = 1'b1;

assign conv8_U0_ap_start = start_for_conv8_U0_empty_n;

assign conv8_U0_start_full_n = 1'b1;

assign conv8_U0_start_write = 1'b0;

assign maxpool1_U0_ap_continue = 1'b1;

assign maxpool1_U0_ap_start = start_for_maxpool1_U0_empty_n;

assign maxpool2_U0_ap_continue = 1'b1;

assign maxpool2_U0_ap_start = start_for_maxpool2_U0_empty_n;

assign maxpool3_U0_ap_continue = 1'b1;

assign maxpool3_U0_ap_start = start_for_maxpool3_U0_empty_n;

assign maxpool4_U0_ap_continue = 1'b1;

assign maxpool4_U0_ap_start = start_for_maxpool4_U0_empty_n;

assign relu_bn1_U0_ap_continue = 1'b1;

assign relu_bn1_U0_ap_start = start_for_relu_bn1_U0_empty_n;

assign relu_bn2_U0_ap_continue = 1'b1;

assign relu_bn2_U0_ap_start = start_for_relu_bn2_U0_empty_n;

assign relu_bn3_U0_ap_continue = 1'b1;

assign relu_bn3_U0_ap_start = start_for_relu_bn3_U0_empty_n;

assign relu_bn4_U0_ap_continue = 1'b1;

assign relu_bn4_U0_ap_start = start_for_relu_bn4_U0_empty_n;

assign relu_bn5_U0_ap_continue = 1'b1;

assign relu_bn5_U0_ap_start = start_for_relu_bn5_U0_empty_n;

assign relu_bn6_U0_ap_continue = 1'b1;

assign relu_bn6_U0_ap_start = start_for_relu_bn6_U0_empty_n;

assign relu_bn7_U0_ap_continue = 1'b1;

assign relu_bn7_U0_ap_start = start_for_relu_bn7_U0_empty_n;

assign relu_bn8_U0_ap_continue = 1'b1;

assign relu_bn8_U0_ap_start = start_for_relu_bn8_U0_empty_n;

assign relu_bn8_U0_start_full_n = 1'b1;

assign relu_bn8_U0_start_write = 1'b0;

assign start_for_conv2_U0_din = 1'b1;

assign start_for_conv3_U0_din = 1'b1;

assign start_for_conv4_U0_din = 1'b1;

assign start_for_conv5_U0_din = 1'b1;

assign start_for_conv6_U0_din = 1'b1;

assign start_for_conv7_U0_din = 1'b1;

assign start_for_conv8_U0_din = 1'b1;

assign start_for_maxpool1_U0_din = 1'b1;

assign start_for_maxpool2_U0_din = 1'b1;

assign start_for_maxpool3_U0_din = 1'b1;

assign start_for_maxpool4_U0_din = 1'b1;

assign start_for_relu_bn1_U0_din = 1'b1;

assign start_for_relu_bn2_U0_din = 1'b1;

assign start_for_relu_bn3_U0_din = 1'b1;

assign start_for_relu_bn4_U0_din = 1'b1;

assign start_for_relu_bn5_U0_din = 1'b1;

assign start_for_relu_bn6_U0_din = 1'b1;

assign start_for_relu_bn7_U0_din = 1'b1;

assign start_for_relu_bn8_U0_din = 1'b1;

endmodule //test
