// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _maxpool3_HH_
#define _maxpool3_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "maxpool3_pool3_likZb.h"
#include "maxpool3_pool3_wik0b.h"

namespace ap_rtl {

struct maxpool3 : public sc_module {
    // Port declarations 16
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_logic > ap_start;
    sc_in< sc_logic > start_full_n;
    sc_out< sc_logic > ap_done;
    sc_in< sc_logic > ap_continue;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;
    sc_out< sc_logic > start_out;
    sc_out< sc_logic > start_write;
    sc_in< sc_lv<5> > relu3_pipe_6_V_V_dout;
    sc_in< sc_logic > relu3_pipe_6_V_V_empty_n;
    sc_out< sc_logic > relu3_pipe_6_V_V_read;
    sc_out< sc_lv<5> > pool3_pipe_6_V_V_din;
    sc_in< sc_logic > pool3_pipe_6_V_V_full_n;
    sc_out< sc_logic > pool3_pipe_6_V_V_write;


    // Module declarations
    maxpool3(sc_module_name name);
    SC_HAS_PROCESS(maxpool3);

    ~maxpool3();

    sc_trace_file* mVcdFile;

    maxpool3_pool3_likZb* pool3_line_buffer_V_U;
    maxpool3_pool3_wik0b* pool3_window_buffer_s_U;
    sc_signal< sc_logic > real_start;
    sc_signal< sc_logic > start_once_reg;
    sc_signal< sc_logic > ap_done_reg;
    sc_signal< sc_lv<13> > ap_CS_fsm;
    sc_signal< sc_logic > ap_CS_fsm_state1;
    sc_signal< sc_logic > internal_ap_ready;
    sc_signal< sc_logic > relu3_pipe_6_V_V_blk_n;
    sc_signal< sc_logic > ap_CS_fsm_state5;
    sc_signal< sc_lv<1> > icmp_ln444_fu_402_p2;
    sc_signal< sc_logic > pool3_pipe_6_V_V_blk_n;
    sc_signal< sc_logic > ap_CS_fsm_state11;
    sc_signal< sc_lv<1> > icmp_ln461_fu_572_p2;
    sc_signal< sc_lv<5> > add_ln439_fu_325_p2;
    sc_signal< sc_lv<5> > add_ln439_reg_639;
    sc_signal< sc_logic > ap_CS_fsm_state2;
    sc_signal< sc_lv<2> > add_ln441_fu_337_p2;
    sc_signal< sc_lv<2> > add_ln441_reg_647;
    sc_signal< sc_logic > ap_CS_fsm_state3;
    sc_signal< sc_lv<9> > add_ln356_fu_367_p2;
    sc_signal< sc_lv<9> > add_ln356_reg_652;
    sc_signal< sc_lv<1> > icmp_ln441_fu_331_p2;
    sc_signal< sc_lv<7> > add_ln442_fu_379_p2;
    sc_signal< sc_lv<7> > add_ln442_reg_660;
    sc_signal< sc_logic > ap_CS_fsm_state4;
    sc_signal< sc_lv<15> > tmp_29_cast_fu_394_p3;
    sc_signal< sc_lv<15> > tmp_29_cast_reg_665;
    sc_signal< sc_lv<1> > icmp_ln442_fu_373_p2;
    sc_signal< sc_lv<7> > add_ln444_fu_408_p2;
    sc_signal< bool > ap_block_state5;
    sc_signal< sc_lv<7> > add_ln451_fu_440_p2;
    sc_signal< sc_lv<7> > add_ln451_reg_684;
    sc_signal< sc_logic > ap_CS_fsm_state7;
    sc_signal< sc_lv<15> > zext_ln454_fu_446_p1;
    sc_signal< sc_lv<15> > zext_ln454_reg_689;
    sc_signal< sc_lv<1> > icmp_ln451_fu_434_p2;
    sc_signal< sc_lv<7> > add_ln450_fu_450_p2;
    sc_signal< sc_lv<2> > add_ln454_fu_462_p2;
    sc_signal< sc_lv<2> > add_ln454_reg_702;
    sc_signal< sc_logic > ap_CS_fsm_state8;
    sc_signal< sc_lv<9> > add_ln356_9_fu_492_p2;
    sc_signal< sc_lv<9> > add_ln356_9_reg_707;
    sc_signal< sc_lv<1> > icmp_ln454_fu_456_p2;
    sc_signal< sc_lv<4> > zext_ln455_1_fu_506_p1;
    sc_signal< sc_lv<4> > zext_ln455_1_reg_712;
    sc_signal< sc_lv<2> > add_ln455_fu_520_p2;
    sc_signal< sc_lv<2> > add_ln455_reg_720;
    sc_signal< sc_logic > ap_CS_fsm_state9;
    sc_signal< sc_lv<4> > add_ln356_10_fu_530_p2;
    sc_signal< sc_lv<4> > add_ln356_10_reg_725;
    sc_signal< sc_lv<1> > icmp_ln455_fu_514_p2;
    sc_signal< sc_lv<2> > add_ln461_fu_578_p2;
    sc_signal< sc_lv<2> > add_ln461_reg_738;
    sc_signal< bool > ap_block_state11;
    sc_signal< sc_lv<4> > zext_ln462_fu_592_p1;
    sc_signal< sc_lv<4> > zext_ln462_reg_743;
    sc_signal< sc_lv<2> > add_ln462_fu_602_p2;
    sc_signal< sc_lv<2> > add_ln462_reg_751;
    sc_signal< sc_logic > ap_CS_fsm_state12;
    sc_signal< sc_lv<1> > icmp_ln462_fu_596_p2;
    sc_signal< sc_lv<5> > select_ln251_fu_628_p3;
    sc_signal< sc_logic > ap_CS_fsm_state13;
    sc_signal< sc_lv<14> > pool3_line_buffer_V_address0;
    sc_signal< sc_logic > pool3_line_buffer_V_ce0;
    sc_signal< sc_logic > pool3_line_buffer_V_we0;
    sc_signal< sc_lv<5> > pool3_line_buffer_V_q0;
    sc_signal< sc_lv<2> > pool3_window_buffer_s_address0;
    sc_signal< sc_logic > pool3_window_buffer_s_ce0;
    sc_signal< sc_logic > pool3_window_buffer_s_we0;
    sc_signal< sc_lv<5> > pool3_window_buffer_s_q0;
    sc_signal< sc_lv<5> > h2_0_0_reg_183;
    sc_signal< bool > ap_block_state1;
    sc_signal< sc_logic > ap_CS_fsm_state6;
    sc_signal< sc_lv<1> > icmp_ln450_fu_428_p2;
    sc_signal< sc_lv<2> > line_row_0_0_reg_194;
    sc_signal< sc_lv<1> > icmp_ln439_fu_319_p2;
    sc_signal< sc_lv<7> > line_col_0_0_reg_205;
    sc_signal< sc_lv<7> > line_c_0_0_reg_216;
    sc_signal< sc_lv<7> > block_0_0_reg_227;
    sc_signal< sc_lv<7> > c_0_0_reg_239;
    sc_signal< sc_lv<2> > window_row_0_0_reg_250;
    sc_signal< sc_lv<2> > window_col_0_0_reg_261;
    sc_signal< sc_logic > ap_CS_fsm_state10;
    sc_signal< sc_lv<5> > tmp_V_9_reg_272;
    sc_signal< sc_lv<2> > pool_row_0_0_reg_285;
    sc_signal< sc_lv<5> > p_0_0_reg_296;
    sc_signal< sc_lv<2> > pool_col_0_0_reg_308;
    sc_signal< sc_lv<64> > zext_ln356_14_fu_423_p1;
    sc_signal< sc_lv<64> > zext_ln356_20_fu_563_p1;
    sc_signal< sc_lv<64> > zext_ln356_18_fu_568_p1;
    sc_signal< sc_lv<64> > zext_ln463_1_fu_617_p1;
    sc_signal< sc_lv<8> > tmp_13_fu_343_p3;
    sc_signal< sc_lv<6> > tmp_14_fu_355_p3;
    sc_signal< sc_lv<9> > zext_ln356_11_fu_363_p1;
    sc_signal< sc_lv<9> > zext_ln356_fu_351_p1;
    sc_signal< sc_lv<9> > zext_ln356_12_fu_385_p1;
    sc_signal< sc_lv<9> > add_ln356_7_fu_389_p2;
    sc_signal< sc_lv<15> > zext_ln356_13_fu_414_p1;
    sc_signal< sc_lv<15> > add_ln356_8_fu_418_p2;
    sc_signal< sc_lv<8> > tmp_15_fu_468_p3;
    sc_signal< sc_lv<6> > tmp_16_fu_480_p3;
    sc_signal< sc_lv<9> > zext_ln356_16_fu_488_p1;
    sc_signal< sc_lv<9> > zext_ln356_15_fu_476_p1;
    sc_signal< sc_lv<3> > tmp_17_fu_498_p3;
    sc_signal< sc_lv<4> > zext_ln356_17_fu_526_p1;
    sc_signal< sc_lv<7> > zext_ln455_fu_510_p1;
    sc_signal< sc_lv<7> > add_ln456_fu_535_p2;
    sc_signal< sc_lv<9> > zext_ln356_19_fu_541_p1;
    sc_signal< sc_lv<9> > add_ln356_11_fu_545_p2;
    sc_signal< sc_lv<15> > tmp_35_cast_fu_550_p3;
    sc_signal< sc_lv<15> > add_ln356_12_fu_558_p2;
    sc_signal< sc_lv<3> > tmp_18_fu_584_p3;
    sc_signal< sc_lv<4> > zext_ln463_fu_608_p1;
    sc_signal< sc_lv<4> > add_ln463_fu_612_p2;
    sc_signal< sc_lv<1> > icmp_ln1494_fu_622_p2;
    sc_signal< sc_lv<13> > ap_NS_fsm;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<13> ap_ST_fsm_state1;
    static const sc_lv<13> ap_ST_fsm_state2;
    static const sc_lv<13> ap_ST_fsm_state3;
    static const sc_lv<13> ap_ST_fsm_state4;
    static const sc_lv<13> ap_ST_fsm_state5;
    static const sc_lv<13> ap_ST_fsm_state6;
    static const sc_lv<13> ap_ST_fsm_state7;
    static const sc_lv<13> ap_ST_fsm_state8;
    static const sc_lv<13> ap_ST_fsm_state9;
    static const sc_lv<13> ap_ST_fsm_state10;
    static const sc_lv<13> ap_ST_fsm_state11;
    static const sc_lv<13> ap_ST_fsm_state12;
    static const sc_lv<13> ap_ST_fsm_state13;
    static const sc_lv<32> ap_const_lv32_0;
    static const sc_lv<32> ap_const_lv32_4;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_lv<32> ap_const_lv32_A;
    static const sc_lv<1> ap_const_lv1_1;
    static const sc_lv<32> ap_const_lv32_1;
    static const sc_lv<32> ap_const_lv32_2;
    static const sc_lv<32> ap_const_lv32_3;
    static const sc_lv<32> ap_const_lv32_6;
    static const sc_lv<32> ap_const_lv32_7;
    static const sc_lv<32> ap_const_lv32_8;
    static const sc_lv<32> ap_const_lv32_B;
    static const sc_lv<32> ap_const_lv32_C;
    static const sc_lv<5> ap_const_lv5_0;
    static const sc_lv<32> ap_const_lv32_5;
    static const sc_lv<2> ap_const_lv2_0;
    static const sc_lv<7> ap_const_lv7_0;
    static const sc_lv<32> ap_const_lv32_9;
    static const sc_lv<5> ap_const_lv5_14;
    static const sc_lv<5> ap_const_lv5_1;
    static const sc_lv<2> ap_const_lv2_2;
    static const sc_lv<2> ap_const_lv2_1;
    static const sc_lv<6> ap_const_lv6_0;
    static const sc_lv<4> ap_const_lv4_0;
    static const sc_lv<7> ap_const_lv7_50;
    static const sc_lv<7> ap_const_lv7_1;
    static const sc_lv<7> ap_const_lv7_40;
    static const sc_lv<7> ap_const_lv7_2;
    static const bool ap_const_boolean_1;
    // Thread declarations
    void thread_ap_clk_no_reset_();
    void thread_add_ln356_10_fu_530_p2();
    void thread_add_ln356_11_fu_545_p2();
    void thread_add_ln356_12_fu_558_p2();
    void thread_add_ln356_7_fu_389_p2();
    void thread_add_ln356_8_fu_418_p2();
    void thread_add_ln356_9_fu_492_p2();
    void thread_add_ln356_fu_367_p2();
    void thread_add_ln439_fu_325_p2();
    void thread_add_ln441_fu_337_p2();
    void thread_add_ln442_fu_379_p2();
    void thread_add_ln444_fu_408_p2();
    void thread_add_ln450_fu_450_p2();
    void thread_add_ln451_fu_440_p2();
    void thread_add_ln454_fu_462_p2();
    void thread_add_ln455_fu_520_p2();
    void thread_add_ln456_fu_535_p2();
    void thread_add_ln461_fu_578_p2();
    void thread_add_ln462_fu_602_p2();
    void thread_add_ln463_fu_612_p2();
    void thread_ap_CS_fsm_state1();
    void thread_ap_CS_fsm_state10();
    void thread_ap_CS_fsm_state11();
    void thread_ap_CS_fsm_state12();
    void thread_ap_CS_fsm_state13();
    void thread_ap_CS_fsm_state2();
    void thread_ap_CS_fsm_state3();
    void thread_ap_CS_fsm_state4();
    void thread_ap_CS_fsm_state5();
    void thread_ap_CS_fsm_state6();
    void thread_ap_CS_fsm_state7();
    void thread_ap_CS_fsm_state8();
    void thread_ap_CS_fsm_state9();
    void thread_ap_block_state1();
    void thread_ap_block_state11();
    void thread_ap_block_state5();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_ready();
    void thread_icmp_ln1494_fu_622_p2();
    void thread_icmp_ln439_fu_319_p2();
    void thread_icmp_ln441_fu_331_p2();
    void thread_icmp_ln442_fu_373_p2();
    void thread_icmp_ln444_fu_402_p2();
    void thread_icmp_ln450_fu_428_p2();
    void thread_icmp_ln451_fu_434_p2();
    void thread_icmp_ln454_fu_456_p2();
    void thread_icmp_ln455_fu_514_p2();
    void thread_icmp_ln461_fu_572_p2();
    void thread_icmp_ln462_fu_596_p2();
    void thread_internal_ap_ready();
    void thread_pool3_line_buffer_V_address0();
    void thread_pool3_line_buffer_V_ce0();
    void thread_pool3_line_buffer_V_we0();
    void thread_pool3_pipe_6_V_V_blk_n();
    void thread_pool3_pipe_6_V_V_din();
    void thread_pool3_pipe_6_V_V_write();
    void thread_pool3_window_buffer_s_address0();
    void thread_pool3_window_buffer_s_ce0();
    void thread_pool3_window_buffer_s_we0();
    void thread_real_start();
    void thread_relu3_pipe_6_V_V_blk_n();
    void thread_relu3_pipe_6_V_V_read();
    void thread_select_ln251_fu_628_p3();
    void thread_start_out();
    void thread_start_write();
    void thread_tmp_13_fu_343_p3();
    void thread_tmp_14_fu_355_p3();
    void thread_tmp_15_fu_468_p3();
    void thread_tmp_16_fu_480_p3();
    void thread_tmp_17_fu_498_p3();
    void thread_tmp_18_fu_584_p3();
    void thread_tmp_29_cast_fu_394_p3();
    void thread_tmp_35_cast_fu_550_p3();
    void thread_zext_ln356_11_fu_363_p1();
    void thread_zext_ln356_12_fu_385_p1();
    void thread_zext_ln356_13_fu_414_p1();
    void thread_zext_ln356_14_fu_423_p1();
    void thread_zext_ln356_15_fu_476_p1();
    void thread_zext_ln356_16_fu_488_p1();
    void thread_zext_ln356_17_fu_526_p1();
    void thread_zext_ln356_18_fu_568_p1();
    void thread_zext_ln356_19_fu_541_p1();
    void thread_zext_ln356_20_fu_563_p1();
    void thread_zext_ln356_fu_351_p1();
    void thread_zext_ln454_fu_446_p1();
    void thread_zext_ln455_1_fu_506_p1();
    void thread_zext_ln455_fu_510_p1();
    void thread_zext_ln462_fu_592_p1();
    void thread_zext_ln463_1_fu_617_p1();
    void thread_zext_ln463_fu_608_p1();
    void thread_ap_NS_fsm();
};

}

using namespace ap_rtl;

#endif
