// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "maxpool4.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic maxpool4::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic maxpool4::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<13> maxpool4::ap_ST_fsm_state1 = "1";
const sc_lv<13> maxpool4::ap_ST_fsm_state2 = "10";
const sc_lv<13> maxpool4::ap_ST_fsm_state3 = "100";
const sc_lv<13> maxpool4::ap_ST_fsm_state4 = "1000";
const sc_lv<13> maxpool4::ap_ST_fsm_state5 = "10000";
const sc_lv<13> maxpool4::ap_ST_fsm_state6 = "100000";
const sc_lv<13> maxpool4::ap_ST_fsm_state7 = "1000000";
const sc_lv<13> maxpool4::ap_ST_fsm_state8 = "10000000";
const sc_lv<13> maxpool4::ap_ST_fsm_state9 = "100000000";
const sc_lv<13> maxpool4::ap_ST_fsm_state10 = "1000000000";
const sc_lv<13> maxpool4::ap_ST_fsm_state11 = "10000000000";
const sc_lv<13> maxpool4::ap_ST_fsm_state12 = "100000000000";
const sc_lv<13> maxpool4::ap_ST_fsm_state13 = "1000000000000";
const sc_lv<32> maxpool4::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> maxpool4::ap_const_lv32_4 = "100";
const sc_lv<1> maxpool4::ap_const_lv1_0 = "0";
const sc_lv<32> maxpool4::ap_const_lv32_A = "1010";
const sc_lv<1> maxpool4::ap_const_lv1_1 = "1";
const sc_lv<32> maxpool4::ap_const_lv32_1 = "1";
const sc_lv<32> maxpool4::ap_const_lv32_2 = "10";
const sc_lv<32> maxpool4::ap_const_lv32_3 = "11";
const sc_lv<32> maxpool4::ap_const_lv32_6 = "110";
const sc_lv<32> maxpool4::ap_const_lv32_7 = "111";
const sc_lv<32> maxpool4::ap_const_lv32_8 = "1000";
const sc_lv<32> maxpool4::ap_const_lv32_B = "1011";
const sc_lv<32> maxpool4::ap_const_lv32_C = "1100";
const sc_lv<4> maxpool4::ap_const_lv4_0 = "0000";
const sc_lv<32> maxpool4::ap_const_lv32_5 = "101";
const sc_lv<2> maxpool4::ap_const_lv2_0 = "00";
const sc_lv<6> maxpool4::ap_const_lv6_0 = "000000";
const sc_lv<7> maxpool4::ap_const_lv7_0 = "0000000";
const sc_lv<32> maxpool4::ap_const_lv32_9 = "1001";
const sc_lv<5> maxpool4::ap_const_lv5_0 = "00000";
const sc_lv<4> maxpool4::ap_const_lv4_A = "1010";
const sc_lv<4> maxpool4::ap_const_lv4_1 = "1";
const sc_lv<2> maxpool4::ap_const_lv2_2 = "10";
const sc_lv<2> maxpool4::ap_const_lv2_1 = "1";
const sc_lv<3> maxpool4::ap_const_lv3_0 = "000";
const sc_lv<6> maxpool4::ap_const_lv6_28 = "101000";
const sc_lv<6> maxpool4::ap_const_lv6_1 = "1";
const sc_lv<7> maxpool4::ap_const_lv7_40 = "1000000";
const sc_lv<7> maxpool4::ap_const_lv7_1 = "1";
const sc_lv<6> maxpool4::ap_const_lv6_2 = "10";
const bool maxpool4::ap_const_boolean_1 = true;

maxpool4::maxpool4(sc_module_name name) : sc_module(name), mVcdFile(0) {
    pool4_line_buffer_V_U = new maxpool4_pool4_liouc("pool4_line_buffer_V_U");
    pool4_line_buffer_V_U->clk(ap_clk);
    pool4_line_buffer_V_U->reset(ap_rst);
    pool4_line_buffer_V_U->address0(pool4_line_buffer_V_address0);
    pool4_line_buffer_V_U->ce0(pool4_line_buffer_V_ce0);
    pool4_line_buffer_V_U->we0(pool4_line_buffer_V_we0);
    pool4_line_buffer_V_U->d0(relu4_pipe_8_V_V_dout);
    pool4_line_buffer_V_U->q0(pool4_line_buffer_V_q0);
    pool4_window_buffer_s_U = new maxpool3_pool3_wik0b("pool4_window_buffer_s_U");
    pool4_window_buffer_s_U->clk(ap_clk);
    pool4_window_buffer_s_U->reset(ap_rst);
    pool4_window_buffer_s_U->address0(pool4_window_buffer_s_address0);
    pool4_window_buffer_s_U->ce0(pool4_window_buffer_s_ce0);
    pool4_window_buffer_s_U->we0(pool4_window_buffer_s_we0);
    pool4_window_buffer_s_U->d0(pool4_line_buffer_V_q0);
    pool4_window_buffer_s_U->q0(pool4_window_buffer_s_q0);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_add_ln356_1_fu_393_p2);
    sensitive << ( add_ln356_reg_656 );
    sensitive << ( zext_ln356_2_fu_389_p1 );

    SC_METHOD(thread_add_ln356_2_fu_422_p2);
    sensitive << ( tmp_19_cast_reg_669 );
    sensitive << ( zext_ln356_3_fu_418_p1 );

    SC_METHOD(thread_add_ln356_3_fu_496_p2);
    sensitive << ( zext_ln356_6_fu_492_p1 );
    sensitive << ( zext_ln356_5_fu_480_p1 );

    SC_METHOD(thread_add_ln356_4_fu_534_p2);
    sensitive << ( zext_ln572_1_reg_716 );
    sensitive << ( zext_ln356_7_fu_530_p1 );

    SC_METHOD(thread_add_ln356_5_fu_549_p2);
    sensitive << ( add_ln356_3_reg_711 );
    sensitive << ( zext_ln356_9_fu_545_p1 );

    SC_METHOD(thread_add_ln356_6_fu_562_p2);
    sensitive << ( zext_ln571_reg_693 );
    sensitive << ( tmp_25_cast_fu_554_p3 );

    SC_METHOD(thread_add_ln356_fu_371_p2);
    sensitive << ( zext_ln356_1_fu_367_p1 );
    sensitive << ( zext_ln356_fu_355_p1 );

    SC_METHOD(thread_add_ln556_fu_329_p2);
    sensitive << ( h3_0_0_reg_187 );

    SC_METHOD(thread_add_ln558_fu_341_p2);
    sensitive << ( line_row_0_0_reg_198 );

    SC_METHOD(thread_add_ln559_fu_383_p2);
    sensitive << ( line_col_0_0_reg_209 );

    SC_METHOD(thread_add_ln561_fu_412_p2);
    sensitive << ( line_c_0_0_reg_220 );

    SC_METHOD(thread_add_ln567_fu_454_p2);
    sensitive << ( block_0_0_reg_231 );

    SC_METHOD(thread_add_ln568_fu_444_p2);
    sensitive << ( c_0_0_reg_243 );

    SC_METHOD(thread_add_ln571_fu_466_p2);
    sensitive << ( window_row_0_0_reg_254 );

    SC_METHOD(thread_add_ln572_fu_524_p2);
    sensitive << ( window_col_0_0_reg_265 );

    SC_METHOD(thread_add_ln573_fu_539_p2);
    sensitive << ( block_0_0_reg_231 );
    sensitive << ( zext_ln572_fu_514_p1 );

    SC_METHOD(thread_add_ln578_fu_582_p2);
    sensitive << ( pool_row_0_0_reg_289 );

    SC_METHOD(thread_add_ln579_fu_606_p2);
    sensitive << ( pool_col_0_0_reg_312 );

    SC_METHOD(thread_add_ln580_fu_616_p2);
    sensitive << ( zext_ln579_reg_747 );
    sensitive << ( zext_ln580_fu_612_p1 );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state10);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state11);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state12);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state13);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state4);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state5);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state6);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state7);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state8);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state9);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_block_state1);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );

    SC_METHOD(thread_ap_block_state11);
    sensitive << ( pool4_pipe_8_V_V_full_n );
    sensitive << ( icmp_ln578_fu_576_p2 );

    SC_METHOD(thread_ap_block_state5);
    sensitive << ( relu4_pipe_8_V_V_empty_n );
    sensitive << ( icmp_ln561_fu_406_p2 );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( icmp_ln556_fu_323_p2 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( real_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( internal_ap_ready );

    SC_METHOD(thread_icmp_ln1494_fu_626_p2);
    sensitive << ( ap_CS_fsm_state13 );
    sensitive << ( pool4_window_buffer_s_q0 );
    sensitive << ( p_0_0_reg_300 );

    SC_METHOD(thread_icmp_ln556_fu_323_p2);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( h3_0_0_reg_187 );

    SC_METHOD(thread_icmp_ln558_fu_335_p2);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( line_row_0_0_reg_198 );

    SC_METHOD(thread_icmp_ln559_fu_377_p2);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( line_col_0_0_reg_209 );

    SC_METHOD(thread_icmp_ln561_fu_406_p2);
    sensitive << ( relu4_pipe_8_V_V_empty_n );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( icmp_ln561_fu_406_p2 );
    sensitive << ( line_c_0_0_reg_220 );

    SC_METHOD(thread_icmp_ln567_fu_432_p2);
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( block_0_0_reg_231 );

    SC_METHOD(thread_icmp_ln568_fu_438_p2);
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( c_0_0_reg_243 );

    SC_METHOD(thread_icmp_ln571_fu_460_p2);
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( window_row_0_0_reg_254 );

    SC_METHOD(thread_icmp_ln572_fu_518_p2);
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( window_col_0_0_reg_265 );

    SC_METHOD(thread_icmp_ln578_fu_576_p2);
    sensitive << ( pool4_pipe_8_V_V_full_n );
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( icmp_ln578_fu_576_p2 );
    sensitive << ( pool_row_0_0_reg_289 );

    SC_METHOD(thread_icmp_ln579_fu_600_p2);
    sensitive << ( ap_CS_fsm_state12 );
    sensitive << ( pool_col_0_0_reg_312 );

    SC_METHOD(thread_internal_ap_ready);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( icmp_ln556_fu_323_p2 );

    SC_METHOD(thread_pool4_line_buffer_V_address0);
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( zext_ln356_4_fu_427_p1 );
    sensitive << ( zext_ln356_10_fu_567_p1 );

    SC_METHOD(thread_pool4_line_buffer_V_ce0);
    sensitive << ( relu4_pipe_8_V_V_empty_n );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( icmp_ln561_fu_406_p2 );
    sensitive << ( ap_CS_fsm_state9 );

    SC_METHOD(thread_pool4_line_buffer_V_we0);
    sensitive << ( relu4_pipe_8_V_V_empty_n );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( icmp_ln561_fu_406_p2 );

    SC_METHOD(thread_pool4_pipe_8_V_V_blk_n);
    sensitive << ( pool4_pipe_8_V_V_full_n );
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( icmp_ln578_fu_576_p2 );

    SC_METHOD(thread_pool4_pipe_8_V_V_din);
    sensitive << ( pool4_pipe_8_V_V_full_n );
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( icmp_ln578_fu_576_p2 );
    sensitive << ( tmp_V_8_reg_276 );

    SC_METHOD(thread_pool4_pipe_8_V_V_write);
    sensitive << ( pool4_pipe_8_V_V_full_n );
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( icmp_ln578_fu_576_p2 );

    SC_METHOD(thread_pool4_window_buffer_s_address0);
    sensitive << ( ap_CS_fsm_state12 );
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( zext_ln356_8_fu_572_p1 );
    sensitive << ( zext_ln580_1_fu_621_p1 );

    SC_METHOD(thread_pool4_window_buffer_s_ce0);
    sensitive << ( ap_CS_fsm_state12 );
    sensitive << ( ap_CS_fsm_state10 );

    SC_METHOD(thread_pool4_window_buffer_s_we0);
    sensitive << ( ap_CS_fsm_state10 );

    SC_METHOD(thread_real_start);
    sensitive << ( ap_start );
    sensitive << ( start_full_n );
    sensitive << ( start_once_reg );

    SC_METHOD(thread_relu4_pipe_8_V_V_blk_n);
    sensitive << ( relu4_pipe_8_V_V_empty_n );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( icmp_ln561_fu_406_p2 );

    SC_METHOD(thread_relu4_pipe_8_V_V_read);
    sensitive << ( relu4_pipe_8_V_V_empty_n );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( icmp_ln561_fu_406_p2 );

    SC_METHOD(thread_select_ln251_fu_632_p3);
    sensitive << ( pool4_window_buffer_s_q0 );
    sensitive << ( p_0_0_reg_300 );
    sensitive << ( icmp_ln1494_fu_626_p2 );

    SC_METHOD(thread_start_out);
    sensitive << ( real_start );

    SC_METHOD(thread_start_write);
    sensitive << ( real_start );
    sensitive << ( start_once_reg );

    SC_METHOD(thread_tmp_10_fu_484_p3);
    sensitive << ( window_row_0_0_reg_254 );

    SC_METHOD(thread_tmp_11_fu_502_p3);
    sensitive << ( window_row_0_0_reg_254 );

    SC_METHOD(thread_tmp_12_fu_588_p3);
    sensitive << ( pool_row_0_0_reg_289 );

    SC_METHOD(thread_tmp_19_cast_fu_398_p3);
    sensitive << ( add_ln356_1_fu_393_p2 );

    SC_METHOD(thread_tmp_1_fu_347_p3);
    sensitive << ( line_row_0_0_reg_198 );

    SC_METHOD(thread_tmp_25_cast_fu_554_p3);
    sensitive << ( add_ln356_5_fu_549_p2 );

    SC_METHOD(thread_tmp_2_fu_359_p3);
    sensitive << ( line_row_0_0_reg_198 );

    SC_METHOD(thread_tmp_9_fu_472_p3);
    sensitive << ( window_row_0_0_reg_254 );

    SC_METHOD(thread_zext_ln356_10_fu_567_p1);
    sensitive << ( add_ln356_6_fu_562_p2 );

    SC_METHOD(thread_zext_ln356_1_fu_367_p1);
    sensitive << ( tmp_2_fu_359_p3 );

    SC_METHOD(thread_zext_ln356_2_fu_389_p1);
    sensitive << ( line_col_0_0_reg_209 );

    SC_METHOD(thread_zext_ln356_3_fu_418_p1);
    sensitive << ( line_c_0_0_reg_220 );

    SC_METHOD(thread_zext_ln356_4_fu_427_p1);
    sensitive << ( add_ln356_2_fu_422_p2 );

    SC_METHOD(thread_zext_ln356_5_fu_480_p1);
    sensitive << ( tmp_9_fu_472_p3 );

    SC_METHOD(thread_zext_ln356_6_fu_492_p1);
    sensitive << ( tmp_10_fu_484_p3 );

    SC_METHOD(thread_zext_ln356_7_fu_530_p1);
    sensitive << ( window_col_0_0_reg_265 );

    SC_METHOD(thread_zext_ln356_8_fu_572_p1);
    sensitive << ( add_ln356_4_reg_729 );

    SC_METHOD(thread_zext_ln356_9_fu_545_p1);
    sensitive << ( add_ln573_fu_539_p2 );

    SC_METHOD(thread_zext_ln356_fu_355_p1);
    sensitive << ( tmp_1_fu_347_p3 );

    SC_METHOD(thread_zext_ln571_fu_450_p1);
    sensitive << ( c_0_0_reg_243 );

    SC_METHOD(thread_zext_ln572_1_fu_510_p1);
    sensitive << ( tmp_11_fu_502_p3 );

    SC_METHOD(thread_zext_ln572_fu_514_p1);
    sensitive << ( window_col_0_0_reg_265 );

    SC_METHOD(thread_zext_ln579_fu_596_p1);
    sensitive << ( tmp_12_fu_588_p3 );

    SC_METHOD(thread_zext_ln580_1_fu_621_p1);
    sensitive << ( add_ln580_fu_616_p2 );

    SC_METHOD(thread_zext_ln580_fu_612_p1);
    sensitive << ( pool_col_0_0_reg_312 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( relu4_pipe_8_V_V_empty_n );
    sensitive << ( pool4_pipe_8_V_V_full_n );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( icmp_ln561_fu_406_p2 );
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( icmp_ln578_fu_576_p2 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( icmp_ln558_fu_335_p2 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( icmp_ln559_fu_377_p2 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( icmp_ln568_fu_438_p2 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( icmp_ln571_fu_460_p2 );
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( icmp_ln572_fu_518_p2 );
    sensitive << ( ap_CS_fsm_state12 );
    sensitive << ( icmp_ln579_fu_600_p2 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( icmp_ln567_fu_432_p2 );
    sensitive << ( icmp_ln556_fu_323_p2 );

    start_once_reg = SC_LOGIC_0;
    ap_done_reg = SC_LOGIC_0;
    ap_CS_fsm = "0000000000001";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "maxpool4_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, start_full_n, "(port)start_full_n");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_continue, "(port)ap_continue");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, start_out, "(port)start_out");
    sc_trace(mVcdFile, start_write, "(port)start_write");
    sc_trace(mVcdFile, relu4_pipe_8_V_V_dout, "(port)relu4_pipe_8_V_V_dout");
    sc_trace(mVcdFile, relu4_pipe_8_V_V_empty_n, "(port)relu4_pipe_8_V_V_empty_n");
    sc_trace(mVcdFile, relu4_pipe_8_V_V_read, "(port)relu4_pipe_8_V_V_read");
    sc_trace(mVcdFile, pool4_pipe_8_V_V_din, "(port)pool4_pipe_8_V_V_din");
    sc_trace(mVcdFile, pool4_pipe_8_V_V_full_n, "(port)pool4_pipe_8_V_V_full_n");
    sc_trace(mVcdFile, pool4_pipe_8_V_V_write, "(port)pool4_pipe_8_V_V_write");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, real_start, "real_start");
    sc_trace(mVcdFile, start_once_reg, "start_once_reg");
    sc_trace(mVcdFile, ap_done_reg, "ap_done_reg");
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, internal_ap_ready, "internal_ap_ready");
    sc_trace(mVcdFile, relu4_pipe_8_V_V_blk_n, "relu4_pipe_8_V_V_blk_n");
    sc_trace(mVcdFile, ap_CS_fsm_state5, "ap_CS_fsm_state5");
    sc_trace(mVcdFile, icmp_ln561_fu_406_p2, "icmp_ln561_fu_406_p2");
    sc_trace(mVcdFile, pool4_pipe_8_V_V_blk_n, "pool4_pipe_8_V_V_blk_n");
    sc_trace(mVcdFile, ap_CS_fsm_state11, "ap_CS_fsm_state11");
    sc_trace(mVcdFile, icmp_ln578_fu_576_p2, "icmp_ln578_fu_576_p2");
    sc_trace(mVcdFile, add_ln556_fu_329_p2, "add_ln556_fu_329_p2");
    sc_trace(mVcdFile, add_ln556_reg_643, "add_ln556_reg_643");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, add_ln558_fu_341_p2, "add_ln558_fu_341_p2");
    sc_trace(mVcdFile, add_ln558_reg_651, "add_ln558_reg_651");
    sc_trace(mVcdFile, ap_CS_fsm_state3, "ap_CS_fsm_state3");
    sc_trace(mVcdFile, add_ln356_fu_371_p2, "add_ln356_fu_371_p2");
    sc_trace(mVcdFile, add_ln356_reg_656, "add_ln356_reg_656");
    sc_trace(mVcdFile, icmp_ln558_fu_335_p2, "icmp_ln558_fu_335_p2");
    sc_trace(mVcdFile, add_ln559_fu_383_p2, "add_ln559_fu_383_p2");
    sc_trace(mVcdFile, add_ln559_reg_664, "add_ln559_reg_664");
    sc_trace(mVcdFile, ap_CS_fsm_state4, "ap_CS_fsm_state4");
    sc_trace(mVcdFile, tmp_19_cast_fu_398_p3, "tmp_19_cast_fu_398_p3");
    sc_trace(mVcdFile, tmp_19_cast_reg_669, "tmp_19_cast_reg_669");
    sc_trace(mVcdFile, icmp_ln559_fu_377_p2, "icmp_ln559_fu_377_p2");
    sc_trace(mVcdFile, add_ln561_fu_412_p2, "add_ln561_fu_412_p2");
    sc_trace(mVcdFile, ap_block_state5, "ap_block_state5");
    sc_trace(mVcdFile, add_ln568_fu_444_p2, "add_ln568_fu_444_p2");
    sc_trace(mVcdFile, add_ln568_reg_688, "add_ln568_reg_688");
    sc_trace(mVcdFile, ap_CS_fsm_state7, "ap_CS_fsm_state7");
    sc_trace(mVcdFile, zext_ln571_fu_450_p1, "zext_ln571_fu_450_p1");
    sc_trace(mVcdFile, zext_ln571_reg_693, "zext_ln571_reg_693");
    sc_trace(mVcdFile, icmp_ln568_fu_438_p2, "icmp_ln568_fu_438_p2");
    sc_trace(mVcdFile, add_ln567_fu_454_p2, "add_ln567_fu_454_p2");
    sc_trace(mVcdFile, add_ln571_fu_466_p2, "add_ln571_fu_466_p2");
    sc_trace(mVcdFile, add_ln571_reg_706, "add_ln571_reg_706");
    sc_trace(mVcdFile, ap_CS_fsm_state8, "ap_CS_fsm_state8");
    sc_trace(mVcdFile, add_ln356_3_fu_496_p2, "add_ln356_3_fu_496_p2");
    sc_trace(mVcdFile, add_ln356_3_reg_711, "add_ln356_3_reg_711");
    sc_trace(mVcdFile, icmp_ln571_fu_460_p2, "icmp_ln571_fu_460_p2");
    sc_trace(mVcdFile, zext_ln572_1_fu_510_p1, "zext_ln572_1_fu_510_p1");
    sc_trace(mVcdFile, zext_ln572_1_reg_716, "zext_ln572_1_reg_716");
    sc_trace(mVcdFile, add_ln572_fu_524_p2, "add_ln572_fu_524_p2");
    sc_trace(mVcdFile, add_ln572_reg_724, "add_ln572_reg_724");
    sc_trace(mVcdFile, ap_CS_fsm_state9, "ap_CS_fsm_state9");
    sc_trace(mVcdFile, add_ln356_4_fu_534_p2, "add_ln356_4_fu_534_p2");
    sc_trace(mVcdFile, add_ln356_4_reg_729, "add_ln356_4_reg_729");
    sc_trace(mVcdFile, icmp_ln572_fu_518_p2, "icmp_ln572_fu_518_p2");
    sc_trace(mVcdFile, add_ln578_fu_582_p2, "add_ln578_fu_582_p2");
    sc_trace(mVcdFile, add_ln578_reg_742, "add_ln578_reg_742");
    sc_trace(mVcdFile, ap_block_state11, "ap_block_state11");
    sc_trace(mVcdFile, zext_ln579_fu_596_p1, "zext_ln579_fu_596_p1");
    sc_trace(mVcdFile, zext_ln579_reg_747, "zext_ln579_reg_747");
    sc_trace(mVcdFile, add_ln579_fu_606_p2, "add_ln579_fu_606_p2");
    sc_trace(mVcdFile, add_ln579_reg_755, "add_ln579_reg_755");
    sc_trace(mVcdFile, ap_CS_fsm_state12, "ap_CS_fsm_state12");
    sc_trace(mVcdFile, icmp_ln579_fu_600_p2, "icmp_ln579_fu_600_p2");
    sc_trace(mVcdFile, select_ln251_fu_632_p3, "select_ln251_fu_632_p3");
    sc_trace(mVcdFile, ap_CS_fsm_state13, "ap_CS_fsm_state13");
    sc_trace(mVcdFile, pool4_line_buffer_V_address0, "pool4_line_buffer_V_address0");
    sc_trace(mVcdFile, pool4_line_buffer_V_ce0, "pool4_line_buffer_V_ce0");
    sc_trace(mVcdFile, pool4_line_buffer_V_we0, "pool4_line_buffer_V_we0");
    sc_trace(mVcdFile, pool4_line_buffer_V_q0, "pool4_line_buffer_V_q0");
    sc_trace(mVcdFile, pool4_window_buffer_s_address0, "pool4_window_buffer_s_address0");
    sc_trace(mVcdFile, pool4_window_buffer_s_ce0, "pool4_window_buffer_s_ce0");
    sc_trace(mVcdFile, pool4_window_buffer_s_we0, "pool4_window_buffer_s_we0");
    sc_trace(mVcdFile, pool4_window_buffer_s_q0, "pool4_window_buffer_s_q0");
    sc_trace(mVcdFile, h3_0_0_reg_187, "h3_0_0_reg_187");
    sc_trace(mVcdFile, ap_block_state1, "ap_block_state1");
    sc_trace(mVcdFile, ap_CS_fsm_state6, "ap_CS_fsm_state6");
    sc_trace(mVcdFile, icmp_ln567_fu_432_p2, "icmp_ln567_fu_432_p2");
    sc_trace(mVcdFile, line_row_0_0_reg_198, "line_row_0_0_reg_198");
    sc_trace(mVcdFile, icmp_ln556_fu_323_p2, "icmp_ln556_fu_323_p2");
    sc_trace(mVcdFile, line_col_0_0_reg_209, "line_col_0_0_reg_209");
    sc_trace(mVcdFile, line_c_0_0_reg_220, "line_c_0_0_reg_220");
    sc_trace(mVcdFile, block_0_0_reg_231, "block_0_0_reg_231");
    sc_trace(mVcdFile, c_0_0_reg_243, "c_0_0_reg_243");
    sc_trace(mVcdFile, window_row_0_0_reg_254, "window_row_0_0_reg_254");
    sc_trace(mVcdFile, window_col_0_0_reg_265, "window_col_0_0_reg_265");
    sc_trace(mVcdFile, ap_CS_fsm_state10, "ap_CS_fsm_state10");
    sc_trace(mVcdFile, tmp_V_8_reg_276, "tmp_V_8_reg_276");
    sc_trace(mVcdFile, pool_row_0_0_reg_289, "pool_row_0_0_reg_289");
    sc_trace(mVcdFile, p_0_0_reg_300, "p_0_0_reg_300");
    sc_trace(mVcdFile, pool_col_0_0_reg_312, "pool_col_0_0_reg_312");
    sc_trace(mVcdFile, zext_ln356_4_fu_427_p1, "zext_ln356_4_fu_427_p1");
    sc_trace(mVcdFile, zext_ln356_10_fu_567_p1, "zext_ln356_10_fu_567_p1");
    sc_trace(mVcdFile, zext_ln356_8_fu_572_p1, "zext_ln356_8_fu_572_p1");
    sc_trace(mVcdFile, zext_ln580_1_fu_621_p1, "zext_ln580_1_fu_621_p1");
    sc_trace(mVcdFile, tmp_1_fu_347_p3, "tmp_1_fu_347_p3");
    sc_trace(mVcdFile, tmp_2_fu_359_p3, "tmp_2_fu_359_p3");
    sc_trace(mVcdFile, zext_ln356_1_fu_367_p1, "zext_ln356_1_fu_367_p1");
    sc_trace(mVcdFile, zext_ln356_fu_355_p1, "zext_ln356_fu_355_p1");
    sc_trace(mVcdFile, zext_ln356_2_fu_389_p1, "zext_ln356_2_fu_389_p1");
    sc_trace(mVcdFile, add_ln356_1_fu_393_p2, "add_ln356_1_fu_393_p2");
    sc_trace(mVcdFile, zext_ln356_3_fu_418_p1, "zext_ln356_3_fu_418_p1");
    sc_trace(mVcdFile, add_ln356_2_fu_422_p2, "add_ln356_2_fu_422_p2");
    sc_trace(mVcdFile, tmp_9_fu_472_p3, "tmp_9_fu_472_p3");
    sc_trace(mVcdFile, tmp_10_fu_484_p3, "tmp_10_fu_484_p3");
    sc_trace(mVcdFile, zext_ln356_6_fu_492_p1, "zext_ln356_6_fu_492_p1");
    sc_trace(mVcdFile, zext_ln356_5_fu_480_p1, "zext_ln356_5_fu_480_p1");
    sc_trace(mVcdFile, tmp_11_fu_502_p3, "tmp_11_fu_502_p3");
    sc_trace(mVcdFile, zext_ln356_7_fu_530_p1, "zext_ln356_7_fu_530_p1");
    sc_trace(mVcdFile, zext_ln572_fu_514_p1, "zext_ln572_fu_514_p1");
    sc_trace(mVcdFile, add_ln573_fu_539_p2, "add_ln573_fu_539_p2");
    sc_trace(mVcdFile, zext_ln356_9_fu_545_p1, "zext_ln356_9_fu_545_p1");
    sc_trace(mVcdFile, add_ln356_5_fu_549_p2, "add_ln356_5_fu_549_p2");
    sc_trace(mVcdFile, tmp_25_cast_fu_554_p3, "tmp_25_cast_fu_554_p3");
    sc_trace(mVcdFile, add_ln356_6_fu_562_p2, "add_ln356_6_fu_562_p2");
    sc_trace(mVcdFile, tmp_12_fu_588_p3, "tmp_12_fu_588_p3");
    sc_trace(mVcdFile, zext_ln580_fu_612_p1, "zext_ln580_fu_612_p1");
    sc_trace(mVcdFile, add_ln580_fu_616_p2, "add_ln580_fu_616_p2");
    sc_trace(mVcdFile, icmp_ln1494_fu_626_p2, "icmp_ln1494_fu_626_p2");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
}

maxpool4::~maxpool4() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete pool4_line_buffer_V_U;
    delete pool4_window_buffer_s_U;
}

void maxpool4::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_done_reg = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_continue.read())) {
            ap_done_reg = ap_const_logic_0;
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
                    esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln556_fu_323_p2.read()))) {
            ap_done_reg = ap_const_logic_1;
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln558_fu_335_p2.read()))) {
        block_0_0_reg_231 = ap_const_lv6_0;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln568_fu_438_p2.read()))) {
        block_0_0_reg_231 = add_ln567_fu_454_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read()) && 
         esl_seteq<1,1,1>(icmp_ln578_fu_576_p2.read(), ap_const_lv1_1) && 
         !(esl_seteq<1,1,1>(icmp_ln578_fu_576_p2.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(ap_const_logic_0, pool4_pipe_8_V_V_full_n.read())))) {
        c_0_0_reg_243 = add_ln568_reg_688.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln567_fu_432_p2.read()))) {
        c_0_0_reg_243 = ap_const_lv7_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln567_fu_432_p2.read()))) {
        h3_0_0_reg_187 = add_ln556_reg_643.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                !(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        h3_0_0_reg_187 = ap_const_lv4_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
         esl_seteq<1,1,1>(icmp_ln561_fu_406_p2.read(), ap_const_lv1_0) && 
         !(esl_seteq<1,1,1>(icmp_ln561_fu_406_p2.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_0, relu4_pipe_8_V_V_empty_n.read())))) {
        line_c_0_0_reg_220 = add_ln561_fu_412_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln559_fu_377_p2.read()))) {
        line_c_0_0_reg_220 = ap_const_lv7_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
         !(esl_seteq<1,1,1>(icmp_ln561_fu_406_p2.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_0, relu4_pipe_8_V_V_empty_n.read())) && 
         esl_seteq<1,1,1>(icmp_ln561_fu_406_p2.read(), ap_const_lv1_1))) {
        line_col_0_0_reg_209 = add_ln559_reg_664.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln558_fu_335_p2.read()))) {
        line_col_0_0_reg_209 = ap_const_lv6_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln559_fu_377_p2.read()))) {
        line_row_0_0_reg_198 = add_ln558_reg_651.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln556_fu_323_p2.read()))) {
        line_row_0_0_reg_198 = ap_const_lv2_0;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read())) {
        p_0_0_reg_300 = select_ln251_fu_632_p3.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read()) && 
                !(esl_seteq<1,1,1>(icmp_ln578_fu_576_p2.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(ap_const_logic_0, pool4_pipe_8_V_V_full_n.read())) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln578_fu_576_p2.read()))) {
        p_0_0_reg_300 = tmp_V_8_reg_276.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read())) {
        pool_col_0_0_reg_312 = add_ln579_reg_755.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read()) && 
                !(esl_seteq<1,1,1>(icmp_ln578_fu_576_p2.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(ap_const_logic_0, pool4_pipe_8_V_V_full_n.read())) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln578_fu_576_p2.read()))) {
        pool_col_0_0_reg_312 = ap_const_lv2_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln571_fu_460_p2.read()))) {
        pool_row_0_0_reg_289 = ap_const_lv2_0;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln579_fu_600_p2.read()))) {
        pool_row_0_0_reg_289 = add_ln578_reg_742.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        start_once_reg = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, real_start.read()) && 
             esl_seteq<1,1,1>(ap_const_logic_0, internal_ap_ready.read()))) {
            start_once_reg = ap_const_logic_1;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, internal_ap_ready.read())) {
            start_once_reg = ap_const_logic_0;
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln571_fu_460_p2.read()))) {
        tmp_V_8_reg_276 = ap_const_lv5_0;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln579_fu_600_p2.read()))) {
        tmp_V_8_reg_276 = p_0_0_reg_300.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read())) {
        window_col_0_0_reg_265 = add_ln572_reg_724.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln571_fu_460_p2.read()))) {
        window_col_0_0_reg_265 = ap_const_lv2_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln572_fu_518_p2.read()))) {
        window_row_0_0_reg_254 = add_ln571_reg_706.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln568_fu_438_p2.read()))) {
        window_row_0_0_reg_254 = ap_const_lv2_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln571_fu_460_p2.read()))) {
        add_ln356_3_reg_711 = add_ln356_3_fu_496_p2.read();
        zext_ln572_1_reg_716 = zext_ln572_1_fu_510_p1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln572_fu_518_p2.read()))) {
        add_ln356_4_reg_729 = add_ln356_4_fu_534_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln558_fu_335_p2.read()))) {
        add_ln356_reg_656 = add_ln356_fu_371_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        add_ln556_reg_643 = add_ln556_fu_329_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        add_ln558_reg_651 = add_ln558_fu_341_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        add_ln559_reg_664 = add_ln559_fu_383_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        add_ln568_reg_688 = add_ln568_fu_444_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        add_ln571_reg_706 = add_ln571_fu_466_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read())) {
        add_ln572_reg_724 = add_ln572_fu_524_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read()) && !(esl_seteq<1,1,1>(icmp_ln578_fu_576_p2.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(ap_const_logic_0, pool4_pipe_8_V_V_full_n.read())))) {
        add_ln578_reg_742 = add_ln578_fu_582_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read())) {
        add_ln579_reg_755 = add_ln579_fu_606_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln559_fu_377_p2.read()))) {
        tmp_19_cast_reg_669 = tmp_19_cast_fu_398_p3.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln568_fu_438_p2.read()))) {
        zext_ln571_reg_693 = zext_ln571_fu_450_p1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read()) && !(esl_seteq<1,1,1>(icmp_ln578_fu_576_p2.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(ap_const_logic_0, pool4_pipe_8_V_V_full_n.read())) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln578_fu_576_p2.read()))) {
        zext_ln579_reg_747 = zext_ln579_fu_596_p1.read();
    }
}

void maxpool4::thread_add_ln356_1_fu_393_p2() {
    add_ln356_1_fu_393_p2 = (!zext_ln356_2_fu_389_p1.read().is_01() || !add_ln356_reg_656.read().is_01())? sc_lv<8>(): (sc_biguint<8>(zext_ln356_2_fu_389_p1.read()) + sc_biguint<8>(add_ln356_reg_656.read()));
}

void maxpool4::thread_add_ln356_2_fu_422_p2() {
    add_ln356_2_fu_422_p2 = (!tmp_19_cast_reg_669.read().is_01() || !zext_ln356_3_fu_418_p1.read().is_01())? sc_lv<14>(): (sc_biguint<14>(tmp_19_cast_reg_669.read()) + sc_biguint<14>(zext_ln356_3_fu_418_p1.read()));
}

void maxpool4::thread_add_ln356_3_fu_496_p2() {
    add_ln356_3_fu_496_p2 = (!zext_ln356_6_fu_492_p1.read().is_01() || !zext_ln356_5_fu_480_p1.read().is_01())? sc_lv<8>(): (sc_biguint<8>(zext_ln356_6_fu_492_p1.read()) + sc_biguint<8>(zext_ln356_5_fu_480_p1.read()));
}

void maxpool4::thread_add_ln356_4_fu_534_p2() {
    add_ln356_4_fu_534_p2 = (!zext_ln356_7_fu_530_p1.read().is_01() || !zext_ln572_1_reg_716.read().is_01())? sc_lv<4>(): (sc_biguint<4>(zext_ln356_7_fu_530_p1.read()) + sc_biguint<4>(zext_ln572_1_reg_716.read()));
}

void maxpool4::thread_add_ln356_5_fu_549_p2() {
    add_ln356_5_fu_549_p2 = (!zext_ln356_9_fu_545_p1.read().is_01() || !add_ln356_3_reg_711.read().is_01())? sc_lv<8>(): (sc_biguint<8>(zext_ln356_9_fu_545_p1.read()) + sc_biguint<8>(add_ln356_3_reg_711.read()));
}

void maxpool4::thread_add_ln356_6_fu_562_p2() {
    add_ln356_6_fu_562_p2 = (!zext_ln571_reg_693.read().is_01() || !tmp_25_cast_fu_554_p3.read().is_01())? sc_lv<14>(): (sc_biguint<14>(zext_ln571_reg_693.read()) + sc_biguint<14>(tmp_25_cast_fu_554_p3.read()));
}

void maxpool4::thread_add_ln356_fu_371_p2() {
    add_ln356_fu_371_p2 = (!zext_ln356_1_fu_367_p1.read().is_01() || !zext_ln356_fu_355_p1.read().is_01())? sc_lv<8>(): (sc_biguint<8>(zext_ln356_1_fu_367_p1.read()) + sc_biguint<8>(zext_ln356_fu_355_p1.read()));
}

void maxpool4::thread_add_ln556_fu_329_p2() {
    add_ln556_fu_329_p2 = (!h3_0_0_reg_187.read().is_01() || !ap_const_lv4_1.is_01())? sc_lv<4>(): (sc_biguint<4>(h3_0_0_reg_187.read()) + sc_biguint<4>(ap_const_lv4_1));
}

void maxpool4::thread_add_ln558_fu_341_p2() {
    add_ln558_fu_341_p2 = (!line_row_0_0_reg_198.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<2>(): (sc_biguint<2>(line_row_0_0_reg_198.read()) + sc_biguint<2>(ap_const_lv2_1));
}

void maxpool4::thread_add_ln559_fu_383_p2() {
    add_ln559_fu_383_p2 = (!line_col_0_0_reg_209.read().is_01() || !ap_const_lv6_1.is_01())? sc_lv<6>(): (sc_biguint<6>(line_col_0_0_reg_209.read()) + sc_biguint<6>(ap_const_lv6_1));
}

void maxpool4::thread_add_ln561_fu_412_p2() {
    add_ln561_fu_412_p2 = (!line_c_0_0_reg_220.read().is_01() || !ap_const_lv7_1.is_01())? sc_lv<7>(): (sc_biguint<7>(line_c_0_0_reg_220.read()) + sc_biguint<7>(ap_const_lv7_1));
}

void maxpool4::thread_add_ln567_fu_454_p2() {
    add_ln567_fu_454_p2 = (!block_0_0_reg_231.read().is_01() || !ap_const_lv6_2.is_01())? sc_lv<6>(): (sc_biguint<6>(block_0_0_reg_231.read()) + sc_biguint<6>(ap_const_lv6_2));
}

void maxpool4::thread_add_ln568_fu_444_p2() {
    add_ln568_fu_444_p2 = (!c_0_0_reg_243.read().is_01() || !ap_const_lv7_1.is_01())? sc_lv<7>(): (sc_biguint<7>(c_0_0_reg_243.read()) + sc_biguint<7>(ap_const_lv7_1));
}

void maxpool4::thread_add_ln571_fu_466_p2() {
    add_ln571_fu_466_p2 = (!window_row_0_0_reg_254.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<2>(): (sc_biguint<2>(window_row_0_0_reg_254.read()) + sc_biguint<2>(ap_const_lv2_1));
}

void maxpool4::thread_add_ln572_fu_524_p2() {
    add_ln572_fu_524_p2 = (!window_col_0_0_reg_265.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<2>(): (sc_biguint<2>(window_col_0_0_reg_265.read()) + sc_biguint<2>(ap_const_lv2_1));
}

void maxpool4::thread_add_ln573_fu_539_p2() {
    add_ln573_fu_539_p2 = (!block_0_0_reg_231.read().is_01() || !zext_ln572_fu_514_p1.read().is_01())? sc_lv<6>(): (sc_biguint<6>(block_0_0_reg_231.read()) + sc_biguint<6>(zext_ln572_fu_514_p1.read()));
}

void maxpool4::thread_add_ln578_fu_582_p2() {
    add_ln578_fu_582_p2 = (!pool_row_0_0_reg_289.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<2>(): (sc_biguint<2>(pool_row_0_0_reg_289.read()) + sc_biguint<2>(ap_const_lv2_1));
}

void maxpool4::thread_add_ln579_fu_606_p2() {
    add_ln579_fu_606_p2 = (!pool_col_0_0_reg_312.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<2>(): (sc_biguint<2>(pool_col_0_0_reg_312.read()) + sc_biguint<2>(ap_const_lv2_1));
}

void maxpool4::thread_add_ln580_fu_616_p2() {
    add_ln580_fu_616_p2 = (!zext_ln579_reg_747.read().is_01() || !zext_ln580_fu_612_p1.read().is_01())? sc_lv<4>(): (sc_biguint<4>(zext_ln579_reg_747.read()) + sc_biguint<4>(zext_ln580_fu_612_p1.read()));
}

void maxpool4::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void maxpool4::thread_ap_CS_fsm_state10() {
    ap_CS_fsm_state10 = ap_CS_fsm.read()[9];
}

void maxpool4::thread_ap_CS_fsm_state11() {
    ap_CS_fsm_state11 = ap_CS_fsm.read()[10];
}

void maxpool4::thread_ap_CS_fsm_state12() {
    ap_CS_fsm_state12 = ap_CS_fsm.read()[11];
}

void maxpool4::thread_ap_CS_fsm_state13() {
    ap_CS_fsm_state13 = ap_CS_fsm.read()[12];
}

void maxpool4::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void maxpool4::thread_ap_CS_fsm_state3() {
    ap_CS_fsm_state3 = ap_CS_fsm.read()[2];
}

void maxpool4::thread_ap_CS_fsm_state4() {
    ap_CS_fsm_state4 = ap_CS_fsm.read()[3];
}

void maxpool4::thread_ap_CS_fsm_state5() {
    ap_CS_fsm_state5 = ap_CS_fsm.read()[4];
}

void maxpool4::thread_ap_CS_fsm_state6() {
    ap_CS_fsm_state6 = ap_CS_fsm.read()[5];
}

void maxpool4::thread_ap_CS_fsm_state7() {
    ap_CS_fsm_state7 = ap_CS_fsm.read()[6];
}

void maxpool4::thread_ap_CS_fsm_state8() {
    ap_CS_fsm_state8 = ap_CS_fsm.read()[7];
}

void maxpool4::thread_ap_CS_fsm_state9() {
    ap_CS_fsm_state9 = ap_CS_fsm.read()[8];
}

void maxpool4::thread_ap_block_state1() {
    ap_block_state1 = (esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1));
}

void maxpool4::thread_ap_block_state11() {
    ap_block_state11 = (esl_seteq<1,1,1>(icmp_ln578_fu_576_p2.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(ap_const_logic_0, pool4_pipe_8_V_V_full_n.read()));
}

void maxpool4::thread_ap_block_state5() {
    ap_block_state5 = (esl_seteq<1,1,1>(icmp_ln561_fu_406_p2.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_0, relu4_pipe_8_V_V_empty_n.read()));
}

void maxpool4::thread_ap_done() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln556_fu_323_p2.read()))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_done_reg.read();
    }
}

void maxpool4::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void maxpool4::thread_ap_ready() {
    ap_ready = internal_ap_ready.read();
}

void maxpool4::thread_icmp_ln1494_fu_626_p2() {
    icmp_ln1494_fu_626_p2 = (!pool4_window_buffer_s_q0.read().is_01() || !p_0_0_reg_300.read().is_01())? sc_lv<1>(): (sc_biguint<5>(pool4_window_buffer_s_q0.read()) > sc_biguint<5>(p_0_0_reg_300.read()));
}

void maxpool4::thread_icmp_ln556_fu_323_p2() {
    icmp_ln556_fu_323_p2 = (!h3_0_0_reg_187.read().is_01() || !ap_const_lv4_A.is_01())? sc_lv<1>(): sc_lv<1>(h3_0_0_reg_187.read() == ap_const_lv4_A);
}

void maxpool4::thread_icmp_ln558_fu_335_p2() {
    icmp_ln558_fu_335_p2 = (!line_row_0_0_reg_198.read().is_01() || !ap_const_lv2_2.is_01())? sc_lv<1>(): sc_lv<1>(line_row_0_0_reg_198.read() == ap_const_lv2_2);
}

void maxpool4::thread_icmp_ln559_fu_377_p2() {
    icmp_ln559_fu_377_p2 = (!line_col_0_0_reg_209.read().is_01() || !ap_const_lv6_28.is_01())? sc_lv<1>(): sc_lv<1>(line_col_0_0_reg_209.read() == ap_const_lv6_28);
}

void maxpool4::thread_icmp_ln561_fu_406_p2() {
    icmp_ln561_fu_406_p2 = (!line_c_0_0_reg_220.read().is_01() || !ap_const_lv7_40.is_01())? sc_lv<1>(): sc_lv<1>(line_c_0_0_reg_220.read() == ap_const_lv7_40);
}

void maxpool4::thread_icmp_ln567_fu_432_p2() {
    icmp_ln567_fu_432_p2 = (!block_0_0_reg_231.read().is_01() || !ap_const_lv6_28.is_01())? sc_lv<1>(): (sc_biguint<6>(block_0_0_reg_231.read()) < sc_biguint<6>(ap_const_lv6_28));
}

void maxpool4::thread_icmp_ln568_fu_438_p2() {
    icmp_ln568_fu_438_p2 = (!c_0_0_reg_243.read().is_01() || !ap_const_lv7_40.is_01())? sc_lv<1>(): sc_lv<1>(c_0_0_reg_243.read() == ap_const_lv7_40);
}

void maxpool4::thread_icmp_ln571_fu_460_p2() {
    icmp_ln571_fu_460_p2 = (!window_row_0_0_reg_254.read().is_01() || !ap_const_lv2_2.is_01())? sc_lv<1>(): sc_lv<1>(window_row_0_0_reg_254.read() == ap_const_lv2_2);
}

void maxpool4::thread_icmp_ln572_fu_518_p2() {
    icmp_ln572_fu_518_p2 = (!window_col_0_0_reg_265.read().is_01() || !ap_const_lv2_2.is_01())? sc_lv<1>(): sc_lv<1>(window_col_0_0_reg_265.read() == ap_const_lv2_2);
}

void maxpool4::thread_icmp_ln578_fu_576_p2() {
    icmp_ln578_fu_576_p2 = (!pool_row_0_0_reg_289.read().is_01() || !ap_const_lv2_2.is_01())? sc_lv<1>(): sc_lv<1>(pool_row_0_0_reg_289.read() == ap_const_lv2_2);
}

void maxpool4::thread_icmp_ln579_fu_600_p2() {
    icmp_ln579_fu_600_p2 = (!pool_col_0_0_reg_312.read().is_01() || !ap_const_lv2_2.is_01())? sc_lv<1>(): sc_lv<1>(pool_col_0_0_reg_312.read() == ap_const_lv2_2);
}

void maxpool4::thread_internal_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln556_fu_323_p2.read()))) {
        internal_ap_ready = ap_const_logic_1;
    } else {
        internal_ap_ready = ap_const_logic_0;
    }
}

void maxpool4::thread_pool4_line_buffer_V_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read())) {
        pool4_line_buffer_V_address0 =  (sc_lv<13>) (zext_ln356_10_fu_567_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        pool4_line_buffer_V_address0 =  (sc_lv<13>) (zext_ln356_4_fu_427_p1.read());
    } else {
        pool4_line_buffer_V_address0 = "XXXXXXXXXXXXX";
    }
}

void maxpool4::thread_pool4_line_buffer_V_ce0() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
          !(esl_seteq<1,1,1>(icmp_ln561_fu_406_p2.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_0, relu4_pipe_8_V_V_empty_n.read()))) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()))) {
        pool4_line_buffer_V_ce0 = ap_const_logic_1;
    } else {
        pool4_line_buffer_V_ce0 = ap_const_logic_0;
    }
}

void maxpool4::thread_pool4_line_buffer_V_we0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
         esl_seteq<1,1,1>(icmp_ln561_fu_406_p2.read(), ap_const_lv1_0) && 
         !(esl_seteq<1,1,1>(icmp_ln561_fu_406_p2.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_0, relu4_pipe_8_V_V_empty_n.read())))) {
        pool4_line_buffer_V_we0 = ap_const_logic_1;
    } else {
        pool4_line_buffer_V_we0 = ap_const_logic_0;
    }
}

void maxpool4::thread_pool4_pipe_8_V_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read()) && 
         esl_seteq<1,1,1>(icmp_ln578_fu_576_p2.read(), ap_const_lv1_1))) {
        pool4_pipe_8_V_V_blk_n = pool4_pipe_8_V_V_full_n.read();
    } else {
        pool4_pipe_8_V_V_blk_n = ap_const_logic_1;
    }
}

void maxpool4::thread_pool4_pipe_8_V_V_din() {
    pool4_pipe_8_V_V_din = tmp_V_8_reg_276.read();
}

void maxpool4::thread_pool4_pipe_8_V_V_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read()) && 
         esl_seteq<1,1,1>(icmp_ln578_fu_576_p2.read(), ap_const_lv1_1) && 
         !(esl_seteq<1,1,1>(icmp_ln578_fu_576_p2.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(ap_const_logic_0, pool4_pipe_8_V_V_full_n.read())))) {
        pool4_pipe_8_V_V_write = ap_const_logic_1;
    } else {
        pool4_pipe_8_V_V_write = ap_const_logic_0;
    }
}

void maxpool4::thread_pool4_window_buffer_s_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read())) {
        pool4_window_buffer_s_address0 =  (sc_lv<2>) (zext_ln580_1_fu_621_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read())) {
        pool4_window_buffer_s_address0 =  (sc_lv<2>) (zext_ln356_8_fu_572_p1.read());
    } else {
        pool4_window_buffer_s_address0 =  (sc_lv<2>) ("XX");
    }
}

void maxpool4::thread_pool4_window_buffer_s_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()))) {
        pool4_window_buffer_s_ce0 = ap_const_logic_1;
    } else {
        pool4_window_buffer_s_ce0 = ap_const_logic_0;
    }
}

void maxpool4::thread_pool4_window_buffer_s_we0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read())) {
        pool4_window_buffer_s_we0 = ap_const_logic_1;
    } else {
        pool4_window_buffer_s_we0 = ap_const_logic_0;
    }
}

void maxpool4::thread_real_start() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, start_full_n.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, start_once_reg.read()))) {
        real_start = ap_const_logic_0;
    } else {
        real_start = ap_start.read();
    }
}

void maxpool4::thread_relu4_pipe_8_V_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
         esl_seteq<1,1,1>(icmp_ln561_fu_406_p2.read(), ap_const_lv1_0))) {
        relu4_pipe_8_V_V_blk_n = relu4_pipe_8_V_V_empty_n.read();
    } else {
        relu4_pipe_8_V_V_blk_n = ap_const_logic_1;
    }
}

void maxpool4::thread_relu4_pipe_8_V_V_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
         esl_seteq<1,1,1>(icmp_ln561_fu_406_p2.read(), ap_const_lv1_0) && 
         !(esl_seteq<1,1,1>(icmp_ln561_fu_406_p2.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_0, relu4_pipe_8_V_V_empty_n.read())))) {
        relu4_pipe_8_V_V_read = ap_const_logic_1;
    } else {
        relu4_pipe_8_V_V_read = ap_const_logic_0;
    }
}

void maxpool4::thread_select_ln251_fu_632_p3() {
    select_ln251_fu_632_p3 = (!icmp_ln1494_fu_626_p2.read()[0].is_01())? sc_lv<5>(): ((icmp_ln1494_fu_626_p2.read()[0].to_bool())? pool4_window_buffer_s_q0.read(): p_0_0_reg_300.read());
}

void maxpool4::thread_start_out() {
    start_out = real_start.read();
}

void maxpool4::thread_start_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, start_once_reg.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, real_start.read()))) {
        start_write = ap_const_logic_1;
    } else {
        start_write = ap_const_logic_0;
    }
}

void maxpool4::thread_tmp_10_fu_484_p3() {
    tmp_10_fu_484_p3 = esl_concat<2,3>(window_row_0_0_reg_254.read(), ap_const_lv3_0);
}

void maxpool4::thread_tmp_11_fu_502_p3() {
    tmp_11_fu_502_p3 = esl_concat<2,1>(window_row_0_0_reg_254.read(), ap_const_lv1_0);
}

void maxpool4::thread_tmp_12_fu_588_p3() {
    tmp_12_fu_588_p3 = esl_concat<2,1>(pool_row_0_0_reg_289.read(), ap_const_lv1_0);
}

void maxpool4::thread_tmp_19_cast_fu_398_p3() {
    tmp_19_cast_fu_398_p3 = esl_concat<8,6>(add_ln356_1_fu_393_p2.read(), ap_const_lv6_0);
}

void maxpool4::thread_tmp_1_fu_347_p3() {
    tmp_1_fu_347_p3 = esl_concat<2,5>(line_row_0_0_reg_198.read(), ap_const_lv5_0);
}

void maxpool4::thread_tmp_25_cast_fu_554_p3() {
    tmp_25_cast_fu_554_p3 = esl_concat<8,6>(add_ln356_5_fu_549_p2.read(), ap_const_lv6_0);
}

void maxpool4::thread_tmp_2_fu_359_p3() {
    tmp_2_fu_359_p3 = esl_concat<2,3>(line_row_0_0_reg_198.read(), ap_const_lv3_0);
}

void maxpool4::thread_tmp_9_fu_472_p3() {
    tmp_9_fu_472_p3 = esl_concat<2,5>(window_row_0_0_reg_254.read(), ap_const_lv5_0);
}

void maxpool4::thread_zext_ln356_10_fu_567_p1() {
    zext_ln356_10_fu_567_p1 = esl_zext<64,14>(add_ln356_6_fu_562_p2.read());
}

void maxpool4::thread_zext_ln356_1_fu_367_p1() {
    zext_ln356_1_fu_367_p1 = esl_zext<8,5>(tmp_2_fu_359_p3.read());
}

void maxpool4::thread_zext_ln356_2_fu_389_p1() {
    zext_ln356_2_fu_389_p1 = esl_zext<8,6>(line_col_0_0_reg_209.read());
}

void maxpool4::thread_zext_ln356_3_fu_418_p1() {
    zext_ln356_3_fu_418_p1 = esl_zext<14,7>(line_c_0_0_reg_220.read());
}

void maxpool4::thread_zext_ln356_4_fu_427_p1() {
    zext_ln356_4_fu_427_p1 = esl_zext<64,14>(add_ln356_2_fu_422_p2.read());
}

void maxpool4::thread_zext_ln356_5_fu_480_p1() {
    zext_ln356_5_fu_480_p1 = esl_zext<8,7>(tmp_9_fu_472_p3.read());
}

void maxpool4::thread_zext_ln356_6_fu_492_p1() {
    zext_ln356_6_fu_492_p1 = esl_zext<8,5>(tmp_10_fu_484_p3.read());
}

void maxpool4::thread_zext_ln356_7_fu_530_p1() {
    zext_ln356_7_fu_530_p1 = esl_zext<4,2>(window_col_0_0_reg_265.read());
}

void maxpool4::thread_zext_ln356_8_fu_572_p1() {
    zext_ln356_8_fu_572_p1 = esl_zext<64,4>(add_ln356_4_reg_729.read());
}

void maxpool4::thread_zext_ln356_9_fu_545_p1() {
    zext_ln356_9_fu_545_p1 = esl_zext<8,6>(add_ln573_fu_539_p2.read());
}

void maxpool4::thread_zext_ln356_fu_355_p1() {
    zext_ln356_fu_355_p1 = esl_zext<8,7>(tmp_1_fu_347_p3.read());
}

void maxpool4::thread_zext_ln571_fu_450_p1() {
    zext_ln571_fu_450_p1 = esl_zext<14,7>(c_0_0_reg_243.read());
}

void maxpool4::thread_zext_ln572_1_fu_510_p1() {
    zext_ln572_1_fu_510_p1 = esl_zext<4,3>(tmp_11_fu_502_p3.read());
}

void maxpool4::thread_zext_ln572_fu_514_p1() {
    zext_ln572_fu_514_p1 = esl_zext<6,2>(window_col_0_0_reg_265.read());
}

void maxpool4::thread_zext_ln579_fu_596_p1() {
    zext_ln579_fu_596_p1 = esl_zext<4,3>(tmp_12_fu_588_p3.read());
}

void maxpool4::thread_zext_ln580_1_fu_621_p1() {
    zext_ln580_1_fu_621_p1 = esl_zext<64,4>(add_ln580_fu_616_p2.read());
}

void maxpool4::thread_zext_ln580_fu_612_p1() {
    zext_ln580_fu_612_p1 = esl_zext<4,2>(pool_col_0_0_reg_312.read());
}

void maxpool4::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && !(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln556_fu_323_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state1;
            } else {
                ap_NS_fsm = ap_ST_fsm_state3;
            }
            break;
        case 4 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln558_fu_335_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state6;
            } else {
                ap_NS_fsm = ap_ST_fsm_state4;
            }
            break;
        case 8 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln559_fu_377_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state3;
            } else {
                ap_NS_fsm = ap_ST_fsm_state5;
            }
            break;
        case 16 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && !(esl_seteq<1,1,1>(icmp_ln561_fu_406_p2.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_0, relu4_pipe_8_V_V_empty_n.read())) && esl_seteq<1,1,1>(icmp_ln561_fu_406_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state4;
            } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && esl_seteq<1,1,1>(icmp_ln561_fu_406_p2.read(), ap_const_lv1_0) && !(esl_seteq<1,1,1>(icmp_ln561_fu_406_p2.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_0, relu4_pipe_8_V_V_empty_n.read())))) {
                ap_NS_fsm = ap_ST_fsm_state5;
            } else {
                ap_NS_fsm = ap_ST_fsm_state5;
            }
            break;
        case 32 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln567_fu_432_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state7;
            }
            break;
        case 64 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln568_fu_438_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state6;
            } else {
                ap_NS_fsm = ap_ST_fsm_state8;
            }
            break;
        case 128 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln571_fu_460_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state11;
            } else {
                ap_NS_fsm = ap_ST_fsm_state9;
            }
            break;
        case 256 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln572_fu_518_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state8;
            } else {
                ap_NS_fsm = ap_ST_fsm_state10;
            }
            break;
        case 512 : 
            ap_NS_fsm = ap_ST_fsm_state9;
            break;
        case 1024 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read()) && esl_seteq<1,1,1>(icmp_ln578_fu_576_p2.read(), ap_const_lv1_1) && !(esl_seteq<1,1,1>(icmp_ln578_fu_576_p2.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(ap_const_logic_0, pool4_pipe_8_V_V_full_n.read())))) {
                ap_NS_fsm = ap_ST_fsm_state7;
            } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read()) && !(esl_seteq<1,1,1>(icmp_ln578_fu_576_p2.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(ap_const_logic_0, pool4_pipe_8_V_V_full_n.read())) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln578_fu_576_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state12;
            } else {
                ap_NS_fsm = ap_ST_fsm_state11;
            }
            break;
        case 2048 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln579_fu_600_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state11;
            } else {
                ap_NS_fsm = ap_ST_fsm_state13;
            }
            break;
        case 4096 : 
            ap_NS_fsm = ap_ST_fsm_state12;
            break;
        default : 
            ap_NS_fsm = "XXXXXXXXXXXXX";
            break;
    }
}

}

